// مكتبة التمارين الافتراضية — Adapted Physical Activity (APA)
import type { Exercise } from './types'

export const DEFAULT_EXERCISES: Omit<Exercise, 'id' | 'createdAt'>[] = [
  // ══════════════════════════════════════════════════════════
  // الفئة العمرية 5-11 سنة
  // ══════════════════════════════════════════════════════════
  {
    title: 'Animal Walk Circuit',
    titleAr: 'دائرة مشية الحيوانات',
    description: 'Children imitate animal movements to develop motor coordination',
    descriptionAr: 'يقلد الأطفال حركات الحيوانات لتطوير التنسيق الحركي',
    category: 'motor',
    ageGroups: ['5-11'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 10,
    points: 30,
    instructions: [
      'Start by walking like a bear (hands and feet on floor)',
      'Switch to frog jumps for 30 seconds',
      'Crawl like a snake for 1 minute',
      'Gallop like a horse to finish',
    ],
    instructionsAr: [
      'ابدأ بالمشي مثل الدب (اليدان والقدمان على الأرض)',
      'انتقل إلى القفز مثل الضفدع لمدة 30 ثانية',
      'ازحف مثل الأفعى لمدة دقيقة',
      'اركض مثل الحصان لإنهاء التمرين',
    ],
    equipment: [],
    contraindications: ['joint pain', 'floor allergies'],
    psychologyObjective: 'Reduce hyperactivity through structured movement with clear rules',
    psychologyObjectiveAr: 'تخفيف فرط الحركة من خلال حركة منظمة بقواعد واضحة',
  },
  {
    title: 'Balance Beam Walk',
    titleAr: 'المشي على خط التوازن',
    description: 'Walking along a line on the floor to improve balance and visual focus',
    descriptionAr: 'المشي على خط مرسوم لتحسين التوازن والتركيز البصري',
    category: 'balance',
    ageGroups: ['5-11'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 8,
    points: 25,
    instructions: [
      'Draw or use tape to make a straight line 3 meters long',
      'Walk heel-to-toe along the line',
      'Try with arms extended for balance',
      'Repeat 5 times, rest between rounds',
    ],
    instructionsAr: [
      'ارسم أو استخدم شريط لصنع خط مستقيم بطول 3 أمتار',
      'امش بوضع كعب القدم أمام أصابع القدم الأخرى',
      'جرب مع مد الذراعين للتوازن',
      'كرر 5 مرات مع الراحة بين الجولات',
    ],
    equipment: ['tape or chalk'],
    contraindications: [],
    psychologyObjective: 'Improve vestibular processing and spatial awareness',
    psychologyObjectiveAr: 'تحسين المعالجة الدهليزية والوعي المكاني',
  },
  {
    title: 'Bubble Breathing',
    titleAr: 'تنفس الفقاعات',
    description: 'Slow breathing exercises using real or imaginary bubbles',
    descriptionAr: 'تمارين التنفس البطيء باستخدام فقاعات حقيقية أو خيالية',
    category: 'focus',
    ageGroups: ['5-11'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 5,
    points: 20,
    instructions: [
      'Sit comfortably and imagine holding a bubble wand',
      'Breathe in slowly through the nose for 4 counts',
      'Breathe out very slowly to "blow the bubble"',
      'Repeat 8 times — try to make each bubble bigger',
    ],
    instructionsAr: [
      'اجلس بشكل مريح وتخيل أنك تمسك عصا الفقاعات',
      'خذ نفساً ببطء من الأنف لعد 4',
      'أخرج الهواء ببطء شديد "لنفخ الفقاعة"',
      'كرر 8 مرات — حاول جعل كل فقاعة أكبر',
    ],
    equipment: ['bubble wand (optional)'],
    contraindications: ['respiratory conditions'],
    psychologyObjective: 'Activate parasympathetic nervous system to reduce anxiety and impulsivity',
    psychologyObjectiveAr: 'تنشيط الجهاز العصبي السمبثاوي لتخفيف القلق والاندفاعية',
  },

  // ══════════════════════════════════════════════════════════
  // الفئة العمرية 12-17 سنة
  // ══════════════════════════════════════════════════════════
  {
    title: 'Rhythm Coordination Drill',
    titleAr: 'تمرين الإيقاع والتنسيق',
    description: 'Clapping and stepping patterns to music to build coordination',
    descriptionAr: 'أنماط التصفيق والخطوات على الموسيقى لبناء التنسيق',
    category: 'motor',
    ageGroups: ['12-17'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 15,
    points: 50,
    instructions: [
      'Play steady rhythm music at 120 BPM',
      'Clap on beat 1 and 3 for 30 seconds',
      'Add step left on beat 1, step right on beat 3',
      'Progress to complex patterns as coordination improves',
    ],
    instructionsAr: [
      'شغّل موسيقى إيقاعية ثابتة',
      'صفق عند الإيقاع 1 و3 لمدة 30 ثانية',
      'أضف خطوة يسار عند 1، خطوة يمين عند 3',
      'تقدم إلى أنماط أكثر تعقيداً عند تحسن التنسيق',
    ],
    equipment: ['music player'],
    contraindications: ['hearing sensitivity'],
    psychologyObjective: 'Improve executive function through rhythmic bilateral coordination',
    psychologyObjectiveAr: 'تحسين الوظيفة التنفيذية من خلال التنسيق الثنائي الإيقاعي',
  },
  {
    title: 'Progressive Muscle Relaxation',
    titleAr: 'الاسترخاء العضلي التدريجي',
    description: 'Systematic tension and release of muscle groups for anxiety relief',
    descriptionAr: 'توتير وإرخاء منهجي لمجموعات العضلات لتخفيف القلق',
    category: 'sensory',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 12,
    points: 40,
    instructions: [
      'Lie down comfortably on a mat',
      'Tense your feet muscles tightly for 5 seconds',
      'Release completely and feel the difference',
      'Move progressively up — calves, thighs, abdomen, arms, face',
    ],
    instructionsAr: [
      'استلقِ بشكل مريح على حصيرة',
      'شدّ عضلات قدميك بقوة لمدة 5 ثوانٍ',
      'أرخِ تماماً وأحسس بالفرق',
      'تقدم تدريجياً للأعلى — الساق، الفخذ، البطن، الذراعين، الوجه',
    ],
    equipment: ['yoga mat'],
    contraindications: ['muscle injuries'],
    psychologyObjective: 'Develop body awareness and reduce cortisol levels through somatic regulation',
    psychologyObjectiveAr: 'تطوير الوعي بالجسم وخفض مستوى الكورتيزول من خلال التنظيم الجسدي',
  },

  // ══════════════════════════════════════════════════════════
  // الفئة العمرية 18-22 سنة
  // ══════════════════════════════════════════════════════════
  {
    title: 'Mindful Strength Circuit',
    titleAr: 'دائرة القوة اليقظة',
    description: 'Bodyweight exercises combined with mindfulness cues',
    descriptionAr: 'تمارين وزن الجسم مع توجيهات اليقظة الذهنية',
    category: 'energy',
    ageGroups: ['18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 20,
    points: 75,
    instructions: [
      'Start with 60 seconds mindful breathing',
      'Perform 10 slow push-ups focusing on every movement',
      '20 squats with deep breathing rhythm',
      '30-second plank with focus on a single point',
      'End with 2 minutes of body scan meditation',
    ],
    instructionsAr: [
      'ابدأ بـ 60 ثانية من التنفس اليقظ',
      'اعمل 10 تمارين ضغط ببطء مع التركيز على كل حركة',
      '20 قرفصاء مع إيقاع التنفس العميق',
      'تمرين الألواح 30 ثانية مع التركيز على نقطة واحدة',
      'اختم بـ 2 دقيقة من مسح الجسم التأملي',
    ],
    equipment: ['yoga mat'],
    contraindications: ['upper body injuries', 'cardiac conditions'],
    psychologyObjective: 'Channel excess energy into structured strength work while building mindfulness capacity',
    psychologyObjectiveAr: 'توجيه الطاقة الزائدة إلى عمل قوة منظم مع بناء قدرة اليقظة الذهنية',
  },
  {
    title: 'Social Movement Game',
    titleAr: 'لعبة الحركة الاجتماعية',
    description: 'Partner or group exercises to practice social interaction through movement',
    descriptionAr: 'تمارين ثنائية أو جماعية لممارسة التفاعل الاجتماعي من خلال الحركة',
    category: 'social',
    ageGroups: ['5-11', '12-17', '18-22'],
    diagnoses: ['AUTISM', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 15,
    points: 60,
    instructions: [
      'Partner A mirrors Partner B movements for 1 minute',
      'Switch roles — B mirrors A',
      'Practice passing a ball with eye contact',
      'Group: form a circle and pass rhythm claps',
    ],
    instructionsAr: [
      'الشريك أ يعكس حركات الشريك ب لمدة دقيقة',
      'بدّل الدور — ب يعكس أ',
      'تدرب على تمرير الكرة مع التواصل البصري',
      'المجموعة: اكوّن دائرة وادور التصفيق الإيقاعي',
    ],
    equipment: ['soft ball'],
    contraindications: [],
    psychologyObjective: 'Develop joint attention, turn-taking, and nonverbal communication through co-movement',
    psychologyObjectiveAr: 'تطوير الانتباه المشترك والتناوب والتواصل غير اللفظي من خلال الحركة المشتركة',
  },
]
