// مكتبة التمارين — Adapted Physical Activity (APA) + تمارين التركيز والانتباه
import type { Exercise } from './types'

export const DEFAULT_EXERCISES: Omit<Exercise, 'id' | 'createdAt'>[] = [

  // ══════════════════════════════════════════════════════════════
  // ① تمارين حركية (Motor) — 5-11 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Animal Walk Circuit',
    titleAr: 'دائرة مشية الحيوانات',
    description: 'Children imitate animal movements to develop motor coordination and burn excess energy',
    descriptionAr: 'يقلد الأطفال حركات الحيوانات لتطوير التنسيق الحركي وتفريغ الطاقة الزائدة',
    category: 'motor',
    ageGroups: ['5-11'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 10,
    points: 30,
    instructions: [
      'Start by walking like a bear (hands and feet on floor)',
      'Switch to frog jumps for 30 seconds',
      'Crawl like a snake for 1 minute',
      'Gallop like a horse to finish',
    ],
    instructionsAr: [
      'ابدأ بالمشي مثل الدب (اليدان والقدمان على الأرض)',
      'انتقل إلى القفز مثل الضفدع لمدة 30 ثانية',
      'ازحف مثل الأفعى لمدة دقيقة',
      'اركض مثل الحصان لإنهاء التمرين',
    ],
    equipment: [],
    contraindications: ['joint pain'],
    psychologyObjective: 'Reduce hyperactivity through structured movement with clear rules',
    psychologyObjectiveAr: 'تخفيف فرط الحركة من خلال حركة منظمة بقواعد واضحة',
  },

  // ══════════════════════════════════════════════════════════════
  // ② تمارين التوازن (Balance) — 5-11 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Balance Beam Walk',
    titleAr: 'المشي على خط التوازن',
    description: 'Walking along a taped line on the floor to improve balance and visual focus',
    descriptionAr: 'المشي على خط شريط لتحسين التوازن والتركيز البصري',
    category: 'balance',
    ageGroups: ['5-11'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 8,
    points: 25,
    instructions: [
      'Use tape to make a straight line 3 meters long on the floor',
      'Walk heel-to-toe along the line without stepping off',
      'Arms extended sideways for balance',
      'Repeat 5 times, rest between rounds',
    ],
    instructionsAr: [
      'ضع شريطاً مستقيماً على الأرض بطول 3 أمتار',
      'امشِ بوضع كعب القدم أمام أصابع القدم الأخرى دون الخروج عن الخط',
      'مد ذراعيك للجانبين للتوازن',
      'كرر 5 مرات مع الراحة بين الجولات',
    ],
    equipment: ['masking tape'],
    contraindications: [],
    psychologyObjective: 'Improve vestibular processing and sustained visual attention',
    psychologyObjectiveAr: 'تحسين المعالجة الدهليزية والانتباه البصري المستمر',
  },

  // ══════════════════════════════════════════════════════════════
  // ③ تمارين التركيز والانتباه — 5-11 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Bubble Breathing',
    titleAr: 'تنفس الفقاعات',
    description: 'Slow diaphragmatic breathing to activate the parasympathetic system and sharpen focus',
    descriptionAr: 'تنفس بطني بطيء لتنشيط الجهاز العصبي السمبثاوي وتحسين التركيز',
    category: 'focus',
    ageGroups: ['5-11'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 5,
    points: 20,
    instructions: [
      'Sit comfortably and imagine holding a bubble wand',
      'Breathe in slowly through the nose for 4 counts',
      'Breathe out very slowly through pursed lips to "blow the bubble" for 8 counts',
      'Repeat 8 times — try to make each bubble bigger',
    ],
    instructionsAr: [
      'اجلس بشكل مريح وتخيل أنك تمسك عصا الفقاعات',
      'خذ نفساً ببطء من الأنف لعد 4',
      'أخرج الهواء ببطء شديد من شفتين مضمومتين لعد 8 "لنفخ الفقاعة"',
      'كرر 8 مرات — حاول جعل كل فقاعة أكبر',
    ],
    equipment: ['bubble wand (optional)'],
    contraindications: ['respiratory conditions'],
    psychologyObjective: 'Activate parasympathetic nervous system; the extended exhale reduces cortisol and prepares prefrontal cortex for focused work',
    psychologyObjectiveAr: 'تنشيط الجهاز العصبي السمبثاوي؛ الزفير الممتد يخفض الكورتيزول ويهيئ الفص الجبهي للتركيز',
  },
  {
    title: 'Stop & Listen Game',
    titleAr: 'لعبة قف واسمع',
    description: 'Selective auditory attention game — child must respond only to a target sound and ignore distractors',
    descriptionAr: 'لعبة الانتباه السمعي الانتقائي — يستجيب الطفل للصوت المستهدف ويتجاهل المشتتات',
    category: 'focus',
    ageGroups: ['5-11'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 8,
    points: 35,
    instructions: [
      'Agree on one target sound (e.g., clap = freeze, snap = jump)',
      'Move freely around the space',
      'Adult makes random sounds — child must identify and respond to target only',
      'Increase speed and add more distractors as child improves',
    ],
    instructionsAr: [
      'اتفق مع الطفل على صوت مستهدف (مثال: تصفيق = تجمّد، طرق = اقفز)',
      'تحرك بحرية في المساحة',
      'يصدر المشرف أصواتاً عشوائية — يجب على الطفل التعرف على الصوت المستهدف فقط والاستجابة له',
      'زد السرعة وأضف مشتتات أكثر كلما تحسّن الطفل',
    ],
    equipment: [],
    contraindications: ['hearing sensitivity'],
    psychologyObjective: 'Train selective attention and inhibitory control — core deficits in ADHD',
    psychologyObjectiveAr: 'تدريب الانتباه الانتقائي وكبح الاستجابة — الجانبان الأساسيان العجزان في ADHD',
  },
  {
    title: 'Target Toss Focus',
    titleAr: 'قذف الهدف المركّز',
    description: 'Throwing a beanbag at numbered targets on the wall — combines sustained attention with motor control',
    descriptionAr: 'رمي كيس القماش على أهداف مرقمة — يجمع بين الانتباه المستمر والتحكم الحركي',
    category: 'focus',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 10,
    points: 40,
    instructions: [
      'Stick numbered circles (1–5) on a wall at different heights',
      'Adult calls a number — child must hit that target only',
      'Stand 2 meters away; increase distance as accuracy improves',
      'Score 5 hits in a row without error = level up',
    ],
    instructionsAr: [
      'الصق دوائر مرقمة (1–5) على الجدار بارتفاعات مختلفة',
      'يصرخ المشرف برقم — يجب على الطفل ضرب ذلك الهدف فقط',
      'الوقوف على بُعد 2 متر؛ زد المسافة مع تحسن الدقة',
      'تسجيل 5 إصابات متتالية دون خطأ = انتقال للمستوى التالي',
    ],
    equipment: ['beanbags', 'colored paper circles', 'tape'],
    contraindications: [],
    psychologyObjective: 'Build sustained attention span and goal-directed behavior through immediate visual feedback',
    psychologyObjectiveAr: 'بناء مدة الانتباه المستمر والسلوك الهادف من خلال التغذية الراجعة البصرية الفورية',
  },
  {
    title: 'Visual Tracking Trail',
    titleAr: 'تمرين تتبع البصر',
    description: 'Follow a slow-moving object with eyes only (no head movement) — foundational for reading and sustained attention',
    descriptionAr: 'تتبع جسم يتحرك ببطء بالعينين فقط (دون تحريك الرأس) — أساسي للقراءة والانتباه المستمر',
    category: 'focus',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 6,
    points: 25,
    instructions: [
      'Child sits still, head held steady',
      'Adult moves a bright pen or small toy slowly in H, X, and circle patterns',
      'Child follows with eyes only — no head turning',
      '3 rounds of 90 seconds, rest 30 seconds between rounds',
    ],
    instructionsAr: [
      'يجلس الطفل بثبات مع تثبيت الرأس',
      'يحرك المشرف قلماً ملوناً أو لعبة صغيرة ببطء في أنماط H و X ودائرة',
      'يتابع الطفل بعينيه فقط — دون تدوير الرأس',
      '3 جولات لمدة 90 ثانية مع راحة 30 ثانية بين الجولات',
    ],
    equipment: ['bright pen or small toy'],
    contraindications: ['visual impairments'],
    psychologyObjective: 'Strengthen oculomotor control and smooth pursuit — directly linked to reading fluency and sustained attention',
    psychologyObjectiveAr: 'تقوية التحكم الحركي للعين والمتابعة السلسة — مرتبطان مباشرة بطلاقة القراءة والانتباه المستمر',
  },

  // ══════════════════════════════════════════════════════════════
  // ④ تمارين الحسية (Sensory) — 5-11 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Sensory Body Scan',
    titleAr: 'مسح الجسم الحسي',
    description: 'Guided body awareness exercise to develop interoception and calm the sensory system',
    descriptionAr: 'تمرين توعية جسدية موجّهة لتطوير الاستقبال الداخلي وتهدئة الجهاز الحسي',
    category: 'sensory',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 8,
    points: 20,
    instructions: [
      'Lie down or sit comfortably with eyes closed',
      'Notice feet — are they warm or cold? Heavy or light?',
      'Move attention slowly upward: ankles, knees, hips, belly, chest, shoulders, face',
      'Take one slow breath at each body part',
    ],
    instructionsAr: [
      'استلقِ أو اجلس بشكل مريح مع إغماض العينين',
      'انتبه للقدمين — هل هما دافئتان أم باردتان؟ ثقيلتان أم خفيفتان؟',
      'انقل الانتباه ببطء للأعلى: الكاحلان، الركبتان، الوركان، البطن، الصدر، الكتفان، الوجه',
      'خذ نفساً بطيئاً عند كل جزء من الجسم',
    ],
    equipment: ['yoga mat'],
    contraindications: [],
    psychologyObjective: 'Develop interoceptive awareness — critical for emotion regulation and self-monitoring in autism spectrum',
    psychologyObjectiveAr: 'تطوير الوعي الاستقبالي الداخلي — أساسي لتنظيم المشاعر والمراقبة الذاتية في طيف التوحد',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑤ تمارين الإيقاع والتنسيق (Motor) — 12-17 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Rhythm Coordination Drill',
    titleAr: 'تمرين الإيقاع والتنسيق',
    description: 'Clapping and stepping patterns to music — builds bilateral coordination and executive function',
    descriptionAr: 'أنماط التصفيق والخطوات على الموسيقى — يبني التنسيق الثنائي والوظيفة التنفيذية',
    category: 'motor',
    ageGroups: ['12-17'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 15,
    points: 50,
    instructions: [
      'Play steady rhythm music at 120 BPM',
      'Clap on beat 1 and 3 for 30 seconds',
      'Add step left on beat 1, step right on beat 3',
      'Progress to complex patterns as coordination improves',
    ],
    instructionsAr: [
      'شغّل موسيقى إيقاعية ثابتة',
      'صفق عند الإيقاع 1 و3 لمدة 30 ثانية',
      'أضف خطوة يسار عند 1، خطوة يمين عند 3',
      'تقدم إلى أنماط أكثر تعقيداً عند تحسن التنسيق',
    ],
    equipment: ['music player'],
    contraindications: ['hearing sensitivity'],
    psychologyObjective: 'Improve executive function through rhythmic bilateral coordination — activates cerebellum-prefrontal circuits',
    psychologyObjectiveAr: 'تحسين الوظيفة التنفيذية من خلال التنسيق الثنائي الإيقاعي — ينشط دوائر المخيخ الجبهية',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑥ تمارين التركيز المتقدمة — 12-17 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Motor Sequencing Challenge',
    titleAr: 'تحدي التسلسل الحركي',
    description: 'Memorise and reproduce increasingly long movement sequences — trains working memory and sustained attention',
    descriptionAr: 'حفظ وإعادة إنتاج تسلسلات حركية متزايدة الطول — يدرّب الذاكرة العاملة والانتباه المستمر',
    category: 'focus',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'intermediate',
    durationMinutes: 12,
    points: 60,
    instructions: [
      'Start with 3-step sequence: clap–jump–touch knees',
      'Child reproduces the sequence immediately after',
      'Add one new movement every 2 successful rounds',
      'Goal: reach 7-step sequence without error',
    ],
    instructionsAr: [
      'ابدأ بتسلسل من 3 خطوات: تصفيق — قفز — لمس الركبتين',
      'يُعيد الطفل التسلسل فوراً بعد رؤيته',
      'أضف حركة جديدة كل جولتين ناجحتين',
      'الهدف: الوصول إلى تسلسل من 7 خطوات دون خطأ',
    ],
    equipment: [],
    contraindications: [],
    psychologyObjective: 'Directly exercise working memory capacity and inhibitory control — the two core executive functions most impaired in ADHD',
    psychologyObjectiveAr: 'تدريب مباشر لسعة الذاكرة العاملة وكبح الاستجابة — أكثر وظيفتين تنفيذيتين تأثراً في ADHD',
  },
  {
    title: 'Box Breathing 4-4-4-4',
    titleAr: 'التنفس الصندوقي 4-4-4-4',
    description: 'Military-grade breathing protocol used by elite forces to achieve rapid mental calm and sharp focus',
    descriptionAr: 'بروتوكول التنفس العسكري المستخدم في القوات الخاصة لتحقيق هدوء ذهني سريع وتركيز حاد',
    category: 'focus',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 6,
    points: 30,
    instructions: [
      'Sit upright, spine tall, feet flat on floor',
      'Exhale completely to empty lungs',
      'Inhale through nose for 4 counts',
      'Hold breath for 4 counts',
      'Exhale through mouth for 4 counts',
      'Hold empty for 4 counts — that is one cycle',
      'Complete 6 full cycles',
    ],
    instructionsAr: [
      'اجلس منتصباً، العمود الفقري مستقيم، القدمان مسطحتان على الأرض',
      'أخرج الهواء تماماً لإفراغ الرئتين',
      'استنشق من الأنف لعد 4',
      'احبس النفس لعد 4',
      'أخرج الهواء من الفم لعد 4',
      'احتفظ بالرئتين فارغتين لعد 4 — هذه دورة واحدة',
      'أكمل 6 دورات كاملة',
    ],
    equipment: [],
    contraindications: ['asthma', 'respiratory conditions'],
    psychologyObjective: 'Rapidly shift autonomic nervous system from sympathetic (fight/flight) to parasympathetic state; proven to reduce anxiety and restore prefrontal cortex function within 90 seconds',
    psychologyObjectiveAr: 'تحويل سريع للجهاز العصبي اللاإرادي من حالة التعاطف (قتال/هروب) إلى حالة السمبثاوي؛ مثبت علمياً في تخفيض القلق واستعادة وظيفة الفص الجبهي خلال 90 ثانية',
  },
  {
    title: 'Focused Listening Protocol',
    titleAr: 'بروتوكول الاستماع المركّز',
    description: 'Selective auditory attention training — identify target sounds within layered background noise',
    descriptionAr: 'تدريب الانتباه السمعي الانتقائي — تحديد الأصوات المستهدفة ضمن ضجيج خلفي متعدد الطبقات',
    category: 'focus',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 10,
    points: 45,
    instructions: [
      'Play ambient background sounds (market, nature)',
      'Instructor reads a list of words — child must tap when hearing a pre-agreed target word category (e.g., "any fruit name")',
      'Start with 60-second clips, increase to 3-minute clips',
      'Track accuracy: hits / total target words × 100%',
    ],
    instructionsAr: [
      'شغّل أصوات خلفية (سوق، طبيعة)',
      'يقرأ المشرف قائمة كلمات — يجب على الطفل النقر عند سماع فئة الكلمة المستهدفة المتفق عليها (مثال: "أي اسم فاكهة")',
      'ابدأ بمقاطع 60 ثانية، زد إلى مقاطع 3 دقائق',
      'تتبع الدقة: الإصابات ÷ إجمالي الكلمات المستهدفة × 100%',
    ],
    equipment: ['audio player'],
    contraindications: ['hearing sensitivity'],
    psychologyObjective: 'Train selective and sustained auditory attention — directly mirrors classroom demands; builds resistance to distraction',
    psychologyObjectiveAr: 'تدريب الانتباه السمعي الانتقائي والمستمر — يحاكي مباشرة متطلبات الفصل الدراسي؛ يبني المقاومة للمشتتات',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑦ الاسترخاء العضلي (Sensory/Regulation) — 12-17, 18-22
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Progressive Muscle Relaxation',
    titleAr: 'الاسترخاء العضلي التدريجي',
    description: 'Systematic tension-and-release of muscle groups — reduces cortisol and prepares the nervous system for focus',
    descriptionAr: 'توتير وإرخاء منهجي لمجموعات العضلات — يخفض الكورتيزول ويهيئ الجهاز العصبي للتركيز',
    category: 'sensory',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 12,
    points: 40,
    instructions: [
      'Lie down comfortably on a mat',
      'Tense your feet muscles tightly for 5 seconds',
      'Release completely and notice the contrast',
      'Move progressively upward: calves → thighs → abdomen → chest → arms → face',
      'Breathe slowly throughout; never hold breath while tensing',
    ],
    instructionsAr: [
      'استلقِ بشكل مريح على حصيرة',
      'شدّ عضلات قدميك بقوة لمدة 5 ثوانٍ',
      'أرخِ تماماً ولاحظ الفرق',
      'تقدم تدريجياً للأعلى: الساق → الفخذ → البطن → الصدر → الذراعان → الوجه',
      'تنفس ببطء طوال التمرين؛ لا تحبس النفس أثناء الشد',
    ],
    equipment: ['yoga mat'],
    contraindications: ['muscle injuries'],
    psychologyObjective: 'Develop somatic self-regulation; body awareness is foundational for recognising and managing emotional dysregulation',
    psychologyObjectiveAr: 'تطوير التنظيم الجسدي الذاتي؛ الوعي بالجسم أساسي للتعرف على ضعف التنظيم العاطفي وإدارته',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑧ تمارين التركيز والانتباه المتقدمة — 18-22 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Mindful Strength Circuit',
    titleAr: 'دائرة القوة اليقظة',
    description: 'Bodyweight exercises fused with mindfulness cues — builds physical strength and mental attention simultaneously',
    descriptionAr: 'تمارين وزن الجسم مع توجيهات اليقظة الذهنية — يبني القوة الجسدية والانتباه الذهني في آنٍ واحد',
    category: 'energy',
    ageGroups: ['18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 20,
    points: 75,
    instructions: [
      'Start with 60 seconds mindful breathing',
      'Perform 10 slow push-ups focusing on every muscle contraction',
      '20 squats with deep breathing rhythm: inhale down, exhale up',
      '30-second plank with full attention on core engagement',
      'End with 2 minutes of body scan meditation',
    ],
    instructionsAr: [
      'ابدأ بـ 60 ثانية من التنفس اليقظ',
      'اعمل 10 تمارين ضغط ببطء مع التركيز على كل تقلص عضلي',
      '20 قرفصاء مع إيقاع تنفس عميق: استنشق عند النزول، أخرج الهواء عند الصعود',
      'تمرين الألواح 30 ثانية مع التركيز الكامل على انقباض العضلة المركزية',
      'اختم بـ 2 دقيقة من مسح الجسم التأملي',
    ],
    equipment: ['yoga mat'],
    contraindications: ['upper body injuries', 'cardiac conditions'],
    psychologyObjective: 'Channel excess energy into structured strength; mindfulness cues force sustained attention during physical effort — a dual-task that significantly improves attentional capacity',
    psychologyObjectiveAr: 'توجيه الطاقة الزائدة لعمل القوة؛ توجيهات اليقظة تُجبر على الانتباه المستمر أثناء المجهود الجسدي — مهمة مزدوجة تحسّن بشكل ملحوظ القدرة الانتباهية',
  },
  {
    title: 'Attention Rebuild Protocol',
    titleAr: 'بروتوكول إعادة بناء الانتباه',
    description: 'Scientifically-structured 20-min session combining breathing, movement bursts, and single-focus tasks to systematically rebuild the attention span',
    descriptionAr: 'جلسة 20 دقيقة مبنية علمياً تجمع التنفس وانفجارات الحركة ومهام التركيز الواحد لإعادة بناء الانتباه بشكل منهجي',
    category: 'focus',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'advanced',
    durationMinutes: 20,
    points: 90,
    instructions: [
      'Phase 1 — Reset (4 min): Box breathing 4-4-4-4 × 4 cycles',
      'Phase 2 — Activate (3 min): 30 jumping jacks at full speed to raise dopamine',
      'Phase 3 — Focus task (8 min): Read a paragraph aloud slowly, one sentence at a time; stop and summarise after each sentence',
      'Phase 4 — Cool down (5 min): Progressive muscle relaxation, starting from feet',
      'Track: how many sentences could you summarise correctly?',
    ],
    instructionsAr: [
      'المرحلة 1 — إعادة الضبط (4 دقائق): التنفس الصندوقي 4-4-4-4 × 4 دورات',
      'المرحلة 2 — التنشيط (3 دقائق): 30 قفزة نجمة بكامل السرعة لرفع الدوبامين',
      'المرحلة 3 — مهمة التركيز (8 دقائق): اقرأ فقرة بصوت عالٍ ببطء، جملة في كل مرة؛ توقف وسرّد ما فهمته بعد كل جملة',
      'المرحلة 4 — التهدئة (5 دقائق): الاسترخاء العضلي التدريجي، ابدأ من القدمين',
      'تتبع: كم جملة تمكنت من تلخيصها بشكل صحيح؟',
    ],
    equipment: ['yoga mat', 'text passage'],
    contraindications: ['cardiac conditions'],
    psychologyObjective: 'Integrates the full neurological reset cycle: parasympathetic activation → dopamine boost → prefrontal engagement → somatic consolidation; evidence base: Ratey J., "Spark" (2008)',
    psychologyObjectiveAr: 'يدمج دورة إعادة الضبط العصبي الكاملة: تنشيط سمبثاوي → رفع دوبامين → إشراك الفص الجبهي → توطيد جسدي؛ المرجع العلمي: Ratey J.، "Spark" (2008)',
  },
  {
    title: 'Distraction Inoculation Training',
    titleAr: 'تدريب التحصين من التشتت',
    description: 'Deliberately practice focusing under increasing distraction conditions — builds distraction immunity for real-world demands',
    descriptionAr: 'ممارسة التركيز عمداً في ظروف مشتتة متزايدة — يبني مناعة التشتت لمتطلبات العالم الحقيقي',
    category: 'focus',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'advanced',
    durationMinutes: 15,
    points: 80,
    instructions: [
      'Choose a 5-minute task requiring sustained attention (drawing, reading, puzzle)',
      'Round 1 — Silent: complete the task in a quiet room, note any mind-wandering',
      'Round 2 — Background: same task with low-level music or noise',
      'Round 3 — Social: same task with someone walking around or talking nearby',
      'After each round: rate focus 1–10 and note what pulled attention away',
    ],
    instructionsAr: [
      'اختر مهمة من 5 دقائق تتطلب انتباهاً مستمراً (رسم، قراءة، لغز)',
      'الجولة 1 — صامت: أكمل المهمة في غرفة هادئة، لاحظ أي تشتت ذهني',
      'الجولة 2 — خلفية: نفس المهمة مع موسيقى أو ضوضاء خفيفة',
      'الجولة 3 — اجتماعي: نفس المهمة مع شخص يتحرك أو يتحدث بالقرب',
      'بعد كل جولة: قيّم التركيز من 1–10 ولاحظ ما سحب انتباهك',
    ],
    equipment: ['age-appropriate focus task materials'],
    contraindications: [],
    psychologyObjective: 'Graduated exposure to distracting stimuli progressively raises the threshold for attentional disruption — same principle as systematic desensitisation applied to the attentional system',
    psychologyObjectiveAr: 'التعرض التدريجي للمثيرات المشتتة يرفع تدريجياً عتبة الاضطراب الانتباهي — نفس مبدأ التحسيس التدريجي المطبق على النظام الانتباهي',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑨ التفاعل الاجتماعي (Social) — جميع الفئات
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Mirror Movement Game',
    titleAr: 'لعبة الحركة المرايا',
    description: 'Partner mirroring exercise — develops joint attention, turn-taking, and nonverbal communication',
    descriptionAr: 'تمرين ثنائي للمرايا — يطور الانتباه المشترك والتناوب والتواصل غير اللفظي',
    category: 'social',
    ageGroups: ['5-11', '12-17', '18-22'],
    diagnoses: ['AUTISM', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 15,
    points: 60,
    instructions: [
      'Partner A leads slow deliberate movements for 60 seconds; Partner B mirrors exactly',
      'Switch roles — B leads, A mirrors',
      'Progress to moving around the room while maintaining mirroring',
      'Final round: both move with no designated leader — find shared rhythm',
    ],
    instructionsAr: [
      'الشريك أ يقود حركات بطيئة ومتعمدة لمدة 60 ثانية؛ الشريك ب يعكسها بدقة',
      'بدّل الدور — ب يقود، أ يعكس',
      'تقدم للتنقل في الغرفة مع الحفاظ على المرايا',
      'الجولة الأخيرة: كلاهما يتحرك بدون قائد محدد — ابحثا معاً عن الإيقاع المشترك',
    ],
    equipment: [],
    contraindications: [],
    psychologyObjective: 'Activate mirror neuron system; sustained joint attention during mirroring directly exercises the attentional systems most challenged in autism spectrum',
    psychologyObjectiveAr: 'تنشيط نظام الخلايا العصبية المرآتية؛ الانتباه المشترك المستمر أثناء التمثيل الحركي يدرّب مباشرة الأنظمة الانتباهية الأكثر تحدياً في طيف التوحد',
  },
  {
    title: 'Cooperative Ball Pass',
    titleAr: 'تمرير الكرة التعاوني',
    description: 'Group exercise using eye contact and timing to pass a ball — builds social attention and impulse control',
    descriptionAr: 'تمرين جماعي باستخدام التواصل البصري والتوقيت لتمرير الكرة — يبني الانتباه الاجتماعي والتحكم في الاندفاع',
    category: 'social',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 12,
    points: 45,
    instructions: [
      'Form a circle of 3–6 participants',
      'Rule: must make eye contact with the receiver BEFORE passing',
      'Start slow with a soft ball; increase pace gradually',
      'Add challenge: two balls simultaneously after mastery',
    ],
    instructionsAr: [
      'اكوّن دائرة من 3–6 مشاركين',
      'القاعدة: يجب التواصل البصري مع المستلم قبل التمرير',
      'ابدأ ببطء مع كرة ناعمة؛ زد السرعة تدريجياً',
      'أضف تحدياً: كرتان في نفس الوقت بعد إتقان المهارة',
    ],
    equipment: ['soft ball(s)'],
    contraindications: [],
    psychologyObjective: 'Eye contact before action forces inhibitory control; cooperative format builds joint attention and social motivation simultaneously',
    psychologyObjectiveAr: 'التواصل البصري قبل الفعل يُجبر على كبح الاستجابة؛ الصيغة التعاونية تبني الانتباه المشترك والدافعية الاجتماعية في آنٍ واحد',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑥ تعديل السلوك — Zone of Regulation (مناطق التنظيم)
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Zone of Regulation Body Check-In',
    titleAr: 'فحص حالتي — مناطق التنظيم الأربع',
    description: 'Child identifies their emotional-arousal zone (Blue/Green/Yellow/Red) using body cues, then chooses a matching calming strategy — the cornerstone of self-regulation',
    descriptionAr: 'يحدد الطفل منطقته العاطفية (أزرق/أخضر/أصفر/أحمر) من إشارات جسمه، ثم يختار استراتيجية تهدئة مناسبة — حجر الأساس لتنظيم الذات',
    category: 'focus',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 10,
    points: 35,
    instructions: [
      'Post the 4-zone chart (Blue=slow/tired, Green=ready/happy, Yellow=wiggling/excited, Red=out-of-control)',
      'Ask: "What does your body feel right now?" — scan heart rate, tension, breathing',
      'Child points to their zone and names 1 body clue (fast heartbeat = Yellow zone)',
      'Together choose a matching tool: Blue→jumping, Yellow→deep breathing, Red→squeeze ball',
      'Practice the chosen tool for 3 minutes, then re-check the zone',
    ],
    instructionsAr: [
      'اعرض مخطط المناطق الأربع: أزرق=بطيء/متعب، أخضر=مستعد/سعيد، أصفر=متحرك/مثار، أحمر=خارج السيطرة',
      'اسأل: "كيف يشعر جسمك الآن؟" — راقب نبضات القلب، التوتر، التنفس',
      'يشير الطفل إلى منطقته ويذكر إشارة جسدية واحدة (قلب سريع = المنطقة الصفراء)',
      'اختارا معاً أداة مناسبة: أزرق→القفز، أصفر→التنفس العميق، أحمر→عصر كرة',
      'مارس الأداة المختارة 3 دقائق ثم أعد فحص المنطقة',
    ],
    equipment: ['zone chart poster', 'stress ball'],
    contraindications: [],
    psychologyObjective: 'Lewin & Kuypers Zone of Regulation framework: builds interoceptive awareness, emotional vocabulary, and self-regulation without shame — bridges feeling and action',
    psychologyObjectiveAr: 'إطار مناطق التنظيم: يبني الوعي الداخلي بالجسم، المفردات العاطفية، والتنظيم الذاتي دون إحساس بالخجل — يجسر الشعور والفعل',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑦ نظام النقاط والمكافآت (Token Economy — ABA)
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Token Economy Daily Chart',
    titleAr: 'نظام النقاط اليومي (بنك المكافآت)',
    description: 'Structured ABA-based token economy: child earns tokens for target behaviors (sitting, following instructions, completing tasks) and exchanges them for meaningful rewards',
    descriptionAr: 'نظام مكافآت ABA منظم: يكسب الطفل رموزاً مقابل السلوكيات المستهدفة (الجلوس، اتباع التعليمات، إنجاز المهام) ويستبدلها بمكافآت ذات معنى',
    category: 'social',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 5,
    points: 50,
    instructions: [
      'Define 3 target behaviors with child: e.g. "stay seated 5 min", "complete one task", "use kind words"',
      'Each success earns 1 star/sticker on the chart — make the reward immediate and specific',
      'Set exchange rate: 5 stars = 10-minute preferred activity, 15 stars = special outing',
      'Review chart together at day\'s end — celebrate every star, never remove earned tokens',
      'Gradually fade tokens as behavior becomes routine (after 3 consistent weeks)',
    ],
    instructionsAr: [
      'حدد 3 سلوكيات هدف مع الطفل: مثل "البقاء جالساً 5 دقائق"، "إنجاز مهمة واحدة"، "استخدام كلمات لطيفة"',
      'كل نجاح يكسب نجمة/ملصقاً على المخطط — اجعل المكافأة فورية ومحددة',
      'حدد معدل الاستبدال: 5 نجوم = 10 دقائق نشاط مفضل، 15 نجمة = نزهة خاصة',
      'راجعا المخطط معاً في نهاية اليوم — احتفل بكل نجمة، لا تسحب الرموز المكتسبة أبداً',
      'قلل الرموز تدريجياً عندما يصبح السلوك روتيناً (بعد 3 أسابيع منتظمة)',
    ],
    equipment: ['star chart', 'stickers', 'reward menu'],
    contraindications: [],
    psychologyObjective: 'Operant conditioning (Skinner): immediate positive reinforcement of specific behaviors builds neural pathways for self-regulation; gradually shifts from extrinsic to intrinsic motivation',
    psychologyObjectiveAr: 'التكييف الإجرائي (سكينر): التعزيز الإيجابي الفوري للسلوكيات المحددة يبني مسارات عصبية للتنظيم الذاتي؛ ينتقل تدريجياً من التحفيز الخارجي إلى الداخلي',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑧ التدخل المعرفي السلوكي — إدارة الغضب (CBT)
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Anger Thermometer & Cool-Down Protocol',
    titleAr: 'ترموميتر الغضب وبروتوكول التهدئة',
    description: 'CBT-based anger management: child learns to identify anger escalation levels 1-10 and applies matched cool-down strategies before reaching the explosion point',
    descriptionAr: 'إدارة الغضب بالعلاج المعرفي السلوكي: يتعلم الطفل تحديد مستويات تصاعد الغضب 1-10 وتطبيق استراتيجيات تهدئة مناسبة قبل الوصول لنقطة الانفجار',
    category: 'focus',
    ageGroups: ['5-11', '12-17', '18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'intermediate',
    durationMinutes: 15,
    points: 45,
    instructions: [
      'Draw anger thermometer together: 1-3=calm, 4-6=frustrated, 7-8=angry, 9-10=explosion',
      'Map body signals to each level: level 5 = clenched fists, racing heart',
      'Assign a strategy to each zone: level 4 = slow breathing, level 7 = walk away + squeeze ball',
      'Role-play a trigger scenario — stop when reaching level 5 and apply the tool',
      'Review: "What was your thermometer at? Did the tool help?" — build metacognitive awareness',
    ],
    instructionsAr: [
      'ارسما معاً ترموميتر الغضب: 1-3=هادئ، 4-6=محبط، 7-8=غاضب، 9-10=انفجار',
      'ضع إشارات الجسم لكل مستوى: المستوى 5 = قبضات مشدودة، قلب متسارع',
      'خصص استراتيجية لكل منطقة: المستوى 4 = التنفس البطيء، المستوى 7 = ابتعد + اعصر الكرة',
      'لعب أدوار مع مثير محاكٍ — توقف عند الوصول للمستوى 5 وطبق الأداة',
      'راجع: "كان ترموميترك عند كم؟ هل ساعدت الأداة؟" — ابنِ الوعي بالتفكير',
    ],
    equipment: ['anger thermometer worksheet', 'stress ball'],
    contraindications: ['acute aggressive episode — wait until calm'],
    psychologyObjective: 'CBT emotional granularity training (Barrett 2017): labeling anger levels with precision reduces amygdala reactivity; matched coping strategies prevent behavioral escalation',
    psychologyObjectiveAr: 'تدريب الدقة العاطفية CBT (باريت 2017): وضع ملصقات دقيقة لمستويات الغضب يقلل من نشاط اللوزة الدماغية؛ استراتيجيات التكيف المناسبة تمنع التصعيد السلوكي',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑨ القصة الاجتماعية (Social Stories — Carol Gray)
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Social Story: The Classroom Transition',
    titleAr: 'القصة الاجتماعية: الانتقال بين الأنشطة',
    description: 'Carol Gray Social Story protocol: a personalized narrative explaining WHY transitions happen and WHAT to do — reduces anxiety and meltdowns during activity changes',
    descriptionAr: 'بروتوكول القصة الاجتماعية: سرد شخصي يشرح لماذا تحدث الانتقالات وماذا أفعل — يقلل القلق والانهيارات خلال تغيير الأنشطة',
    category: 'social',
    ageGroups: ['5-11'],
    diagnoses: ['AUTISM', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 10,
    points: 30,
    instructions: [
      'Write the story using 4 sentence types: Descriptive ("When the bell rings..."), Perspective ("My teacher wants me to..."), Directive ("I can take 3 deep breaths..."), Affirmative ("This helps everyone")',
      'Illustrate with the child\'s own drawings or photos',
      'Read it 3x per day for 2 weeks — morning, before the transition, and at bedtime',
      'After the actual transition, ask: "Remember the story? What did you do?"',
      'Celebrate success with the token chart — reinforce the story-guided behavior',
    ],
    instructionsAr: [
      'اكتب القصة بـ4 أنواع جمل: وصفية ("عندما يرن الجرس...")، منظور ("معلمي يريد مني...")، توجيهية ("يمكنني أخذ 3 أنفاس عميقة...")، تأكيدية ("هذا يساعد الجميع")',
      'صوّر القصة برسوم الطفل أو صوره الشخصية',
      'اقرأها 3 مرات يومياً لأسبوعين — الصباح، قبل الانتقال، وقت النوم',
      'بعد الانتقال الفعلي، اسأل: "تذكرت القصة؟ ماذا فعلت؟"',
      'احتفل بالنجاح في مخطط النقاط — عزز السلوك المستوحى من القصة',
    ],
    equipment: ['story booklet', 'photos or drawings'],
    contraindications: [],
    psychologyObjective: 'Carol Gray Social Stories (1993): provides missing social context for autistic children, reduces theory-of-mind demand, and creates cognitive scripts that bridge intention and action',
    psychologyObjectiveAr: 'القصص الاجتماعية كارول غراي (1993): توفر السياق الاجتماعي المفقود للأطفال التوحديين، تقلل متطلبات نظرية العقل، وتنشئ نصوصاً إدراكية تجسر النية والفعل',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑩ تدريب الذاكرة العاملة (Cogmed-style Working Memory)
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Reverse Sequence Challenge',
    titleAr: 'تحدي التسلسل المعكوس',
    description: 'Cogmed-inspired working memory training: child repeats sequences of numbers/movements in reverse order, progressively challenging the central executive system',
    descriptionAr: 'تدريب الذاكرة العاملة: يكرر الطفل تسلسلات من الأرقام/الحركات بالترتيب المعكوس، مع تحدٍ تدريجي للنظام التنفيذي المركزي',
    category: 'focus',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 12,
    points: 50,
    instructions: [
      'Start with 2-digit reverse: say "3-7", child repeats "7-3" — 3 correct = level up',
      'Add movement: tap head=1, touch shoulder=2, stomp=3 — perform sequence in reverse',
      'Progress to 4-step sequences when 3 consecutive successes achieved',
      'Keep sessions short (10 min max) — cognitive fatigue degrades performance quality',
      'Record longest successful reverse span — celebrate new personal records',
    ],
    instructionsAr: [
      'ابدأ بعكس رقمين: قل "3-7"، يكرر الطفل "7-3" — 3 صحيحة = ارتقِ مستوى',
      'أضف حركة: اضرب الرأس=1، المس الكتف=2، الدوس=3 — أدِّ التسلسل معكوساً',
      'تقدم إلى 4 خطوات عند تحقيق 3 نجاحات متتالية',
      'أبقِ الجلسات قصيرة (10 دقائق كحد أقصى) — الإرهاق الإدراكي يدهور جودة الأداء',
      'سجّل أطول امتداد عكسي ناجح — احتفل بالأرقام القياسية الشخصية',
    ],
    equipment: ['score card'],
    contraindications: [],
    psychologyObjective: 'Baddeley\'s working memory model: phonological loop + visuospatial sketchpad training via reverse span increases central executive capacity, shown to reduce ADHD symptoms (Cogmed meta-analysis, 2014)',
    psychologyObjectiveAr: 'نموذج الذاكرة العاملة لباديلي: تدريب الحلقة الصوتية والمفكرة البصرية عبر الامتداد المعكوس يزيد سعة المدير التنفيذي المركزي، ثبت تقليله أعراض ADHD (تحليل كوغميد، 2014)',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑪ برنامج المهارات الاجتماعية PEERS (لـ 12-22 سنة)
  // ══════════════════════════════════════════════════════════════
  {
    title: 'PEERS Conversation Entry Protocol',
    titleAr: 'بروتوكول بدء المحادثة (PEERS)',
    description: 'Evidence-based PEERS social skills protocol for teens: step-by-step rules for joining conversations, managing awkward silences, and exiting gracefully',
    descriptionAr: 'بروتوكول المهارات الاجتماعية PEERS للمراهقين: قواعد خطوة بخطوة للانضمام للمحادثات، التعامل مع الصمت المحرج، والخروج بلباقة',
    category: 'social',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['AUTISM', 'ADHD', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 20,
    points: 60,
    instructions: [
      'Step 1 — Look for conversational entry points: group of 2-3, open body language, laughter',
      'Step 2 — Listen to topic first (10-15 seconds) before speaking',
      'Step 3 — Use a casual comment related to what they said: "That\'s funny, I heard..." or "Oh really? I think..."',
      'Step 4 — Ask 1 follow-up question to show interest: "Have you tried...?"',
      'Step 5 — Exit gracefully: "I have to go, but it was great talking to you!"',
      'Role-play each step with the professor, then with a peer',
    ],
    instructionsAr: [
      'الخطوة 1 — ابحث عن فرص الدخول: مجموعة 2-3، لغة جسد منفتحة، ضحك',
      'الخطوة 2 — استمع للموضوع أولاً (10-15 ثانية) قبل الكلام',
      'الخطوة 3 — استخدم تعليقاً غير رسمي مرتبطاً بما قيل: "هذا مضحك، سمعت..." أو "آه حقاً؟ أعتقد..."',
      'الخطوة 4 — اطرح سؤالاً متابعاً لإظهار الاهتمام: "هل جربت...؟"',
      'الخطوة 5 — اخرج بلباقة: "يجب أن أذهب، لكن كان من الرائع التحدث معك!"',
      'لعب دور لكل خطوة مع الأستاذ، ثم مع أحد الأقران',
    ],
    equipment: ['conversation cards'],
    contraindications: [],
    psychologyObjective: 'PEERS UCLA protocol (Laugeson 2014): only evidence-based social skills program with RCT for ASD teens showing 88% success in friendship quality at 5-year follow-up',
    psychologyObjectiveAr: 'بروتوكول PEERS جامعة UCLA (لوجيسون 2014): البرنامج الوحيد للمهارات الاجتماعية المعتمد بدراسة عشوائية مضبوطة يُظهر نجاحاً 88% في جودة الصداقة في متابعة 5 سنوات',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑫ تدريب الوظيفة التنفيذية — التخطيط والتنظيم
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Task Tower: Breaking Down Goals',
    titleAr: 'برج المهام: تحليل الأهداف',
    description: 'Executive function training: child learns to decompose a large task into small, timed sub-tasks using a visual tower model — builds planning, initiation, and task persistence',
    descriptionAr: 'تدريب الوظيفة التنفيذية: يتعلم الطفل تحليل مهمة كبيرة إلى مهام فرعية صغيرة موقوتة باستخدام نموذج البرج البصري — يبني التخطيط، المبادرة، والمثابرة',
    category: 'focus',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 20,
    points: 55,
    instructions: [
      'Choose a task the child finds overwhelming (homework, cleaning room)',
      'Draw a tower with 5-7 blocks — each block = one small sub-task (5-10 min max)',
      'Estimate time for each block together, then set a visible timer',
      'Work one block at a time — cross off completed blocks (dopamine reward from visual progress)',
      'Allow a 2-minute movement break between blocks',
      'Debrief: "Which block was hardest? What helped you start?"',
    ],
    instructionsAr: [
      'اختر مهمة يجدها الطفل ساحقة (واجبات، ترتيب الغرفة)',
      'ارسم برجاً من 5-7 مكعبات — كل مكعب = مهمة فرعية صغيرة (5-10 دقائق كحد أقصى)',
      'اقدّرا الوقت لكل مكعب معاً، ثم ضع مؤقتاً مرئياً',
      'اعمل مكعباً واحداً في كل مرة — شطّب المكعبات المنجزة (مكافأة الدوبامين من التقدم البصري)',
      'اسمح بفترة حركة 2 دقيقة بين المكعبات',
      'ناقش: "أي مكعب كان الأصعب؟ ما الذي ساعدك على البدء؟"',
    ],
    equipment: ['task tower worksheet', 'visual timer'],
    contraindications: [],
    psychologyObjective: 'Barkley\'s self-regulation model: externalizing time and goals compensates for ADHD\'s temporal blindness; chunking activates dopamine reward circuits on completion of each sub-task',
    psychologyObjectiveAr: 'نموذج التنظيم الذاتي لباركلي: إخراج الوقت والأهداف للخارج يعوض عمى الوقت في ADHD؛ التقسيم يُنشّط دوائر مكافأة الدوبامين عند إنجاز كل مهمة فرعية',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑬ اليقظة الذهنية للأطفال (Mindfulness-ADHD)
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Mindful Movement: Walking Meditation',
    titleAr: 'الحركة اليقظة: التأمل المشي',
    description: 'MBSR-adapted mindfulness for ADHD: slow mindful walking with full body-scan attention — anchors wandering mind using kinesthetic input, not stillness',
    descriptionAr: 'اليقظة الذهنية المعدلة للـ ADHD: المشي البطيء اليقظ مع انتباه مسح الجسم الكامل — يُرسّخ العقل الهائم باستخدام المدخلات الحركية، لا السكون',
    category: 'focus',
    ageGroups: ['5-11', '12-17', '18-22'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 8,
    points: 30,
    instructions: [
      'Walk VERY slowly — each step takes 5 seconds: lift heel, move leg, place toe, then heel',
      'Narrate out loud: "I feel the floor under my left heel... I notice my knee bending..."',
      'When mind wanders (it will), gently return: "Back to my foot, now..."',
      'Count steps silently from 1 to 10, then restart — structured counting prevents boredom',
      'End with 1 minute standing: "Feel both feet on the ground. Notice 3 things you can hear"',
    ],
    instructionsAr: [
      'امشِ ببطء شديد — كل خطوة تأخذ 5 ثوانٍ: ارفع الكعب، حرك الساق، ضع إصبع القدم، ثم الكعب',
      'صف بصوت عالٍ: "أشعر بالأرض تحت كعبي الأيسر... ألاحظ ركبتي تنثني..."',
      'عندما يتشتت الذهن (وسيحدث)، ارجع بلطف: "عودة إلى قدمي، الآن..."',
      'عدّ الخطوات بصمت من 1 إلى 10 ثم أعد — العدد المنظم يمنع الملل',
      'أنهِ بدقيقة واقفاً: "أشعر بكلتا قدميَّ على الأرض. ألاحظ 3 أشياء أسمعها"',
    ],
    equipment: ['quiet floor space (2-3 meters)'],
    contraindications: [],
    psychologyObjective: 'Zylowska MindfulADHD protocol: movement-based mindfulness bypasses the stillness barrier in ADHD; kinesthetic anchor + verbal narration recruits prefrontal cortex without demanding prolonged inhibition',
    psychologyObjectiveAr: 'بروتوكول اليقظة الذهنية لـ ADHD (زيلوفسكا): اليقظة القائمة على الحركة تتجاوز حاجز السكون في ADHD؛ المرتكز الحركي + السرد اللفظي يُجنّد قشرة الفص الجبهي دون طلب تثبيط مطوّل',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑭ إيقاع الجسم والتنسيق (Interactive Metronome)
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Rhythmic Beat Synchronization',
    titleAr: 'مزامنة الإيقاع الحركي',
    description: 'Interactive Metronome-inspired exercise: synchronizing claps/stomps to a beat trains neural timing networks, directly improving attention, impulse control, and motor coordination',
    descriptionAr: 'تمرين مستوحى من الميترونوم التفاعلي: مزامنة التصفيق/الدوس مع الإيقاع يدرّب شبكات التوقيت العصبي، مما يحسن مباشرة الانتباه وكبح الاندفاعية والتنسيق الحركي',
    category: 'motor',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 12,
    points: 40,
    instructions: [
      'Set metronome to 60 BPM — simple hand clap to every beat for 1 minute',
      'Increase complexity: clap-clap-stomp pattern, synced to beat',
      'Add bilateral component: alternate right hand then left hand on beat',
      'Partner variation: professor and child clap alternately on the beat',
      'Challenge mode: professor varies tempo — child must immediately re-sync',
    ],
    instructionsAr: [
      'اضبط الميترونوم على 60 نبضة/دقيقة — تصفيق بسيط مع كل نبضة لمدة دقيقة',
      'زد التعقيد: نمط تصفيق-تصفيق-دوس، متزامن مع الإيقاع',
      'أضف مكوناً ثنائي الجانب: اليد اليمنى ثم اليسرى بالتناوب مع النبضة',
      'تنويع مع شريك: الأستاذ والطفل يتناوبان التصفيق على الإيقاع',
      'وضع التحدي: الأستاذ يغيّر الإيقاع — يجب على الطفل إعادة المزامنة فوراً',
    ],
    equipment: ['metronome app (free)', 'floor space'],
    contraindications: ['hearing impairment — use visual metronome'],
    psychologyObjective: 'Interactive Metronome studies (Shaffer 2001): timing training reduces ADHD symptoms by 35% through cerebellar-prefrontal loop strengthening, improving temporal processing fundamental to attention and impulse control',
    psychologyObjectiveAr: 'دراسات الميترونوم التفاعلي (شافر 2001): يقلل تدريب التوقيت أعراض ADHD بنسبة 35% عبر تقوية الحلقة المخيخية-الجبهية، مما يحسن المعالجة الزمنية الأساسية للانتباه وكبح الاندفاعية',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑮ التكامل الحسي — بروتوكول ويلبارجر
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Deep Pressure & Proprioceptive Reset',
    titleAr: 'بروتوكول الضغط العميق وإعادة ضبط الحس العميق',
    description: 'Wilbarger Deep Pressure Protocol: structured deep-touch input to arms/back/legs calms the nervous system within 90 seconds — evidence-based sensory diet for hyper/hyposensitive children',
    descriptionAr: 'بروتوكول ويلبارجر للضغط العميق: مدخلات لمس عميق منظمة على الذراعين/الظهر/الساقين تهدئ الجهاز العصبي في 90 ثانية — نظام غذاء حسي معتمد للأطفال فرطي/ناقصي الحساسية',
    category: 'sensory',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['AUTISM', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 5,
    points: 25,
    instructions: [
      'Use a soft brush or hands with firm, even pressure — never light tickling strokes',
      'Sequence: both arms (front→back), upper back, both legs (front→back) — 10 strokes each',
      'Immediately follow with 10 joint compressions: press shoulders down gently 10 times',
      'Child tells you: "1-2-3" pressure = too light, "4-5-6" = just right, "7-8-9" = too hard',
      'Repeat every 2 hours if needed — establish as pre-activity calming routine',
    ],
    instructionsAr: [
      'استخدم فرشاة ناعمة أو يدين بضغط ثابت وموحد — لا تربيتات خفيفة مدغدغة أبداً',
      'التسلسل: كلا الذراعين (أمام→خلف)، أعلى الظهر، كلا الساقين (أمام→خلف) — 10 حركات لكل جزء',
      'أعقِب مباشرة بـ10 ضغطات على المفاصل: اضغط على الكتفين للأسفل برفق 10 مرات',
      'يخبرك الطفل: "1-2-3" ضغط = خفيف جداً، "4-5-6" = مناسب تماماً، "7-8-9" = قوي جداً',
      'كرر كل ساعتين إذا لزم — أسّسه كروتين تهدئة قبل الأنشطة',
    ],
    equipment: ['soft tactile brush (or dry hands)'],
    contraindications: ['tactile defensiveness — introduce gradually', 'broken skin'],
    psychologyObjective: 'Ayres Sensory Integration: proprioceptive and deep tactile input modulates reticular activating system arousal, reducing sensory overload and increasing nervous system readiness for learning',
    psychologyObjectiveAr: 'التكامل الحسي أيرز: المدخلات الحس عميق واللمس العميق تنظم إثارة نظام التنشيط الشبكي، تقلل الحمل الحسي الزائد وتزيد جاهزية الجهاز العصبي للتعلم',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑯ تمرين رد الفعل (Reaction Training) — جميع الفئات
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Reaction Time Training',
    titleAr: 'تدريب سرعة رد الفعل',
    description: 'Digital reaction-time game: a target flashes on screen at random intervals — child taps it as fast as possible, training sustained attention and processing speed',
    descriptionAr: 'لعبة رد الفعل الرقمية: يظهر هدف على الشاشة في فترات عشوائية — يضغط الطفل عليه بأسرع ما يمكن، مما يدرب الانتباه المستمر وسرعة المعالجة',
    category: 'focus',
    ageGroups: ['5-11', '12-17', '18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 5,
    points: 30,
    instructions: [
      'Open the reaction game on the tablet/screen',
      'Tap the green target the moment it appears — do NOT tap before it appears',
      'Each game has 10 trials; average reaction time is tracked',
      'Goal: improve average below 400ms over multiple sessions',
      'Compare session-to-session to show the child their real progress',
    ],
    instructionsAr: [
      'افتح لعبة رد الفعل على الجهاز اللوحي/الشاشة',
      'اضغط الهدف الأخضر فور ظهوره — لا تضغط قبل ظهوره',
      'كل لعبة تحتوي 10 محاولات؛ يتم تتبع متوسط وقت رد الفعل',
      'الهدف: تحسين المتوسط إلى أقل من 400ms عبر جلسات متعددة',
      'قارن بين الجلسات لإظهار التقدم الحقيقي للطفل',
    ],
    equipment: ['tablet or computer with reaction game'],
    contraindications: [],
    psychologyObjective: 'Processing speed and sustained alertness training — directly targets the attentional lapses common in ADHD; reaction time is a biomarker of executive function efficiency',
    psychologyObjectiveAr: 'تدريب سرعة المعالجة واليقظة المستمرة — يستهدف مباشرة الثغرات الانتباهية الشائعة في ADHD؛ وقت رد الفعل مؤشر حيوي لكفاءة الوظيفة التنفيذية',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑰ الألعاب الحركية التكيفية (Ball Skills) — 5-17 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Balloon Keep-Up Challenge',
    titleAr: 'تحدي إبقاء البالون في الهواء',
    description: 'Keep a balloon airborne using only one hand — combines sustained attention, motor coordination, and fun for all ability levels',
    descriptionAr: 'إبقاء البالون في الهواء باستخدام يد واحدة فقط — يجمع الانتباه المستمر والتنسيق الحركي والمتعة لجميع مستويات القدرة',
    category: 'motor',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 8,
    points: 25,
    instructions: [
      'Start with right hand only — how many hits before it touches the floor?',
      'Switch to left hand only — aim to match the right hand score',
      'Level 2: alternate hands — right, left, right, left',
      'Level 3: use a small pool noodle instead of hand for a longer lever challenge',
      'Record and beat personal best each session',
    ],
    instructionsAr: [
      'ابدأ باليد اليمنى فقط — كم لمسة قبل سقوط البالون؟',
      'انتقل لليد اليسرى فقط — اهدف لتحقيق نفس نتيجة اليد اليمنى',
      'المستوى 2: بدّل بين اليدين — يمين، يسار، يمين، يسار',
      'المستوى 3: استخدم عصا نودل بدلاً من اليد لتحدٍ أطول',
      'سجّل وكسر الرقم القياسي الشخصي في كل جلسة',
    ],
    equipment: ['balloon'],
    contraindications: [],
    psychologyObjective: 'Sustained attention + immediate feedback loop: every missed balloon gives instant failure signal forcing re-engagement; bilateral coordination activates both brain hemispheres simultaneously',
    psychologyObjectiveAr: 'حلقة الانتباه المستمر + التغذية الراجعة الفورية: كل بالون فائت يعطي إشارة فشل فورية تجبر على إعادة الانتباه؛ التنسيق الثنائي ينشط كلا نصفي الدماغ في آنٍ واحد',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑱ التمييز السمعي (Animal Sounds) — 5-11 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Animal Sound Discrimination',
    titleAr: 'التمييز بين أصوات الحيوانات',
    description: 'Play animal sounds and child must identify which animal — develops auditory discrimination, categorisation, and language skills',
    descriptionAr: 'شغّل أصوات الحيوانات ويجب على الطفل تحديد الحيوان — يطور التمييز السمعي والتصنيف ومهارات اللغة',
    category: 'sensory',
    ageGroups: ['5-11'],
    diagnoses: ['AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 10,
    points: 30,
    instructions: [
      'Use a sound app or YouTube clips of real animal sounds',
      'Play 3-second clip — child must name the animal or point to picture',
      'Start with 4 contrasting animals (dog, cat, bird, cow)',
      'Progress to similar-sounding animals (goat/sheep, duck/goose)',
      'Add challenge: play 2 sounds simultaneously — which animal did you hear?',
    ],
    instructionsAr: [
      'استخدم تطبيق أصوات أو مقاطع يوتيوب لأصوات حيوانات حقيقية',
      'شغّل مقطعاً لمدة 3 ثوانٍ — يجب على الطفل تسمية الحيوان أو الإشارة لصورته',
      'ابدأ بـ4 حيوانات متباينة (كلب، قطة، طائر، بقرة)',
      'تقدم لحيوانات متشابهة الصوت (ماعز/خروف، بطة/وز)',
      'أضف تحدياً: شغّل صوتين في آنٍ واحد — أي حيوان سمعت؟',
    ],
    equipment: ['tablet with animal sounds app', 'animal picture cards'],
    contraindications: ['high audio sensitivity — use low volume'],
    psychologyObjective: 'Auditory processing and categorisation training: children with autism often show atypical auditory processing; explicit discrimination tasks build the neural pathways for filtering meaningful sounds from noise',
    psychologyObjectiveAr: 'تدريب المعالجة السمعية والتصنيف: يُظهر أطفال التوحد غالباً معالجة سمعية غير نمطية؛ مهام التمييز الصريح تبني المسارات العصبية لتصفية الأصوات الهادفة من الضوضاء',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑲ الكبح الحركي — Simon Says (القائد يقول) — 5-11 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Simon Says — Advanced Inhibition',
    titleAr: 'سايمون يقول — كبح متقدم',
    description: 'Classic Simon Says with progressive inhibition demands — child must follow instructions ONLY when prefaced with "Simon Says", resisting the urge to copy otherwise',
    descriptionAr: 'لعبة سايمون يقول الكلاسيكية مع متطلبات كبح متزايدة — يجب اتباع التعليمات فقط عند البدء بـ"سايمون يقول"، مقاومة اندفاع التقليد',
    category: 'focus',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 12,
    points: 45,
    instructions: [
      'Establish the rule: only move when you hear "Simon says" first',
      'Round 1 — Slow: give 2 seconds between instructions, deliberate voice',
      'Round 2 — Speed: rapid-fire instructions every 1 second, mix trick commands (no "Simon says")',
      'Round 3 — Reverse: now DON\'T do it when "Simon says" — do it when there\'s no prefix',
      'Track: how many errors per round? Goal is to reduce errors each game',
    ],
    instructionsAr: [
      'أرسخ القاعدة: تحرك فقط عند سماع "سايمون يقول" أولاً',
      'الجولة 1 — بطيء: أعطِ ثانيتين بين التعليمات، صوت متعمد',
      'الجولة 2 — سرعة: تعليمات سريعة كل ثانية، امزج أوامر حيلة (بدون "سايمون يقول")',
      'الجولة 3 — معكوس: الآن لا تفعله عند "سايمون يقول" — افعله عند غياب البادئة',
      'تتبع: كم خطأ في كل جولة؟ الهدف تقليل الأخطاء في كل لعبة',
    ],
    equipment: [],
    contraindications: [],
    psychologyObjective: 'Inhibitory control via conditional rule-following: the "not Simon says" error is a classic commission error mirroring impulsivity in ADHD; the reverse round maximally challenges the central executive',
    psychologyObjectiveAr: 'كبح الاستجابة عبر اتباع القواعد المشروطة: خطأ "ليس سايمون يقول" خطأ كبح نموذجي يعكس الاندفاعية في ADHD؛ الجولة المعكوسة تتحدى المدير التنفيذي المركزي بالحد الأقصى',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑳ التتبع البصري الرقمي — تمرين الكمبيوتر/اللوحي
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Digital Tracking & Scan',
    titleAr: 'التتبع البصري الرقمي',
    description: 'On-screen exercise: child tracks a moving target with their finger or stylus without losing it — trains oculomotor control and sustained visual attention',
    descriptionAr: 'تمرين على الشاشة: يتتبع الطفل هدفاً متحركاً بإصبعه أو قلمه الرقمي دون فقدانه — يدرب التحكم بالعين والانتباه البصري المستمر',
    category: 'focus',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 6,
    points: 25,
    instructions: [
      'Open a simple tracking app or use the session platform\'s tap-target exercise',
      'Child must follow the moving target continuously without looking away',
      'Session 1: slow speed, large target',
      'Session 2: medium speed, smaller target',
      'Session 3: fast speed, multiple distractors on screen',
    ],
    instructionsAr: [
      'افتح تطبيق التتبع البسيط أو استخدم لعبة الهدف في منصة الجلسة',
      'يجب على الطفل متابعة الهدف المتحرك باستمرار دون النظر بعيداً',
      'الجلسة 1: سرعة بطيئة، هدف كبير',
      'الجلسة 2: سرعة متوسطة، هدف أصغر',
      'الجلسة 3: سرعة عالية، مشتتات متعددة على الشاشة',
    ],
    equipment: ['tablet with touch screen'],
    contraindications: ['screen light sensitivity'],
    psychologyObjective: 'Smooth pursuit eye movement training activates frontal eye fields and improves sustained visual attention — foundational for reading, driving, and social eye contact',
    psychologyObjectiveAr: 'تدريب حركة العين التتبعية السلسة يُنشّط الحقول الأمامية للعين ويحسن الانتباه البصري المستمر — أساسي للقراءة والقيادة والتواصل البصري الاجتماعي',
  },

  // ══════════════════════════════════════════════════════════════
  // ㉑ الرياضة المعدلة — السباحة المعدلة (APA Swimming)
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Adapted Swimming Program',
    titleAr: 'برنامج السباحة المعدلة',
    description: 'Adapted aquatic therapy protocol: rhythmic swimming movements provide deep proprioceptive input, regulate the nervous system, and dramatically reduce ADHD and anxiety symptoms',
    descriptionAr: 'بروتوكول العلاج المائي المعدل: الحركات الإيقاعية للسباحة توفر مدخلات حس عميق، تنظم الجهاز العصبي، وتقلل بشكل ملحوظ أعراض ADHD والقلق',
    category: 'motor',
    ageGroups: ['5-11', '12-17', '18-22'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 45,
    points: 100,
    instructions: [
      'Phase 1 — Water Entry (5 min): slow entry with breathing control, no splashing',
      'Phase 2 — Floating (10 min): back float with guided breathing, feel water support',
      'Phase 3 — Rhythmic Kicks (15 min): wall kicks with consistent rhythm — count to 20 then rest',
      'Phase 4 — Free Swim (10 min): choose preferred stroke, focus on breathing rhythm',
      'Phase 5 — Cool Down (5 min): slow widths with mindful breathing, exit slowly',
    ],
    instructionsAr: [
      'المرحلة 1 — الدخول (5 دقائق): دخول بطيء مع التحكم في التنفس، بدون رش',
      'المرحلة 2 — الطفو (10 دقائق): طفو على الظهر مع التنفس الموجّه، الشعور بدعم الماء',
      'المرحلة 3 — ركلات إيقاعية (15 دقيقة): ركلات على الحائط بإيقاع ثابت — عد إلى 20 ثم استرح',
      'المرحلة 4 — سباحة حرة (10 دقائق): اختر أسلوبك المفضل، ركز على إيقاع التنفس',
      'المرحلة 5 — التهدئة (5 دقائق): عرضيات بطيئة مع تنفس يقظ، اخرج ببطء',
    ],
    equipment: ['swimming pool', 'kickboard', 'nose clip if needed'],
    contraindications: ['ear infections', 'open wounds', 'seizure disorder without supervision'],
    psychologyObjective: 'Water\'s hydrostatic pressure provides full-body deep pressure equivalent to weighted vest therapy; rhythmic bilateral movements activate cerebellum-prefrontal circuits; 20 min of aerobic swimming = 3-4 hour ADHD symptom reduction (Verret 2012)',
    psychologyObjectiveAr: 'ضغط الماء الهيدروستاتيكي يوفر ضغطاً عميقاً كاملاً للجسم مكافئاً لعلاج السترة الثقيلة؛ الحركات الثنائية الإيقاعية تنشط دوائر المخيخ-الجبهية؛ 20 دقيقة سباحة هوائية = تخفيض أعراض ADHD لـ4-3 ساعات (فيريت 2012)',
  },

  // ══════════════════════════════════════════════════════════════
  // ㉒ مهارات الحياة اليومية (ADL) — 12-22 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Daily Routine Mastery',
    titleAr: 'إتقان الروتين اليومي',
    description: 'Step-by-step training for daily routines (morning, homework, bedtime) using visual schedules and backward chaining — builds independence and reduces family conflict',
    descriptionAr: 'تدريب خطوة بخطوة على الروتين اليومي (الصباح، الواجبات، النوم) باستخدام الجداول المرئية والتسلسل العكسي — يبني الاستقلالية ويقلل الصراع الأسري',
    category: 'social',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 15,
    points: 40,
    instructions: [
      'Choose one routine (morning is usually most impacted) — list every step with child',
      'Create visual checklist: photos or simple drawings, not just words',
      'Practice the LAST step first (backward chaining) — this guarantees at least one success',
      'Use a visual timer (Time Timer) so child can see time shrinking — not just hear warnings',
      'Week 1: professor guides. Week 2: prompts only. Week 3: independent with checklist. Week 4: fade checklist',
    ],
    instructionsAr: [
      'اختر روتيناً واحداً (الصباح عادةً الأكثر تأثراً) — اصنع قائمة بكل خطوة مع الطفل',
      'اصنع قائمة تحقق مرئية: صور أو رسوم بسيطة، ليس فقط كلمات',
      'مارس الخطوة الأخيرة أولاً (تسلسل عكسي) — هذا يضمن نجاحاً واحداً على الأقل',
      'استخدم مؤقتاً مرئياً حتى يرى الطفل الوقت ينتهي — ليس فقط سماع التحذيرات',
      'الأسبوع 1: إشراف أستاذ. الأسبوع 2: توجيهات فقط. الأسبوع 3: مستقل مع القائمة. الأسبوع 4: تقليل القائمة',
    ],
    equipment: ['visual schedule cards', 'visual timer (Time Timer brand)', 'sticker reward chart'],
    contraindications: [],
    psychologyObjective: 'Externalizing executive function: visual schedules compensate for ADHD\'s working memory deficits; backward chaining (Skinner 1938) ensures mastery at each step before adding the next, preventing learned helplessness',
    psychologyObjectiveAr: 'إخراج الوظيفة التنفيذية: الجداول المرئية تعوض عن عجز الذاكرة العاملة في ADHD؛ التسلسل العكسي (سكينر 1938) يضمن الإتقان في كل خطوة قبل إضافة التالية، مانعاً العجز المكتسب',
  },

  // ══════════════════════════════════════════════════════════════
  // ㉓ اليوغا المعدلة للأطفال (Yoga for ADHD/Autism)
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Kids Yoga Flow — Focus & Calm',
    titleAr: 'يوغا الأطفال — التركيز والهدوء',
    description: 'Adapted yoga sequence using animal poses — combines body awareness, breathing, and vestibular input to calm the nervous system and sharpen focus',
    descriptionAr: 'تسلسل يوغا معدل بأوضاع الحيوانات — يجمع الوعي بالجسم والتنفس والمدخلات الدهليزية لتهدئة الجهاز العصبي وتحسين التركيز',
    category: 'balance',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 15,
    points: 45,
    instructions: [
      'Cat-Cow (1 min): on hands and knees, arch back up (cat) then sag down (cow), sync with breathing',
      'Warrior I (1 min each side): step forward, arms up, hold still — feel the strength',
      'Tree Pose (1 min each foot): balance on one foot, hands in prayer — use a wall if needed',
      'Downward Dog (1 min): hips up, back flat, push through hands — child calls it "mountain pose"',
      'Corpse Pose / Relaxation (3 min): lie flat, eyes closed, no movement — professor narrates body scan',
    ],
    instructionsAr: [
      'القطة-البقرة (دقيقة): على اليدين والركبتين، قوّس الظهر للأعلى (قطة) ثم للأسفل (بقرة)، زامن مع التنفس',
      'المحارب الأول (دقيقة لكل جانب): تقدم للأمام، ارفع الذراعين، اثبت — أشعر بالقوة',
      'وضع الشجرة (دقيقة لكل قدم): توازن على قدم واحدة، يدان في وضع الصلاة — استخدم الجدار إذا لزم',
      'الكلب المنحني للأسفل (دقيقة): الوركان للأعلى، الظهر مستقيم، ادفع عبر اليدين',
      'وضع الجثة/الاسترخاء (3 دقائق): استلقِ مسطحاً، أعين مغلقة، لا حركة — يسرد الأستاذ مسح الجسم',
    ],
    equipment: ['yoga mat or soft floor'],
    contraindications: ['joint hypermobility — avoid deep stretches', 'balance disorders without support'],
    psychologyObjective: 'Jensen & Kenny (2004) RCT: 20-session yoga program reduced ADHD symptoms by 31%; vestibular input from balance poses + controlled breathing activates parasympathetic system within 90 seconds',
    psychologyObjectiveAr: 'تجربة معشاة (جنسن وكيني 2004): برنامج يوغا 20 جلسة قلّص أعراض ADHD بنسبة 31%؛ المدخلات الدهليزية من أوضاع التوازن + التنفس المتحكم ينشط الجهاز السمبثاوي في 90 ثانية',
  },

  // ══════════════════════════════════════════════════════════════
  // ㉔ الإدراك المكاني (Spatial Awareness) — 5-17 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Obstacle Navigation Course',
    titleAr: 'دورة التنقل بين العقبات',
    description: 'Navigate a simple obstacle course using verbal instructions — builds spatial reasoning, body awareness, and the ability to follow multi-step directions',
    descriptionAr: 'التنقل في دورة عقبات بسيطة باستخدام تعليمات لفظية — يبني التفكير المكاني والوعي بالجسم والقدرة على اتباع توجيهات متعددة الخطوات',
    category: 'motor',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 12,
    points: 35,
    instructions: [
      'Set up 5-7 obstacles using chairs, cones, cushions, or tape lines',
      'Give verbal-only instructions: "Go around the red chair, UNDER the rope, then step ON each dot"',
      'Child must remember the full sequence before starting (working memory load)',
      'Time each run — aim to reduce errors before reducing time',
      'Blindfold variation (older children): navigate using only verbal guidance from professor',
    ],
    instructionsAr: [
      'ضع 5-7 عقبات باستخدام كراسي، أقماع، وسائد، أو خطوط شريط',
      'أعطِ تعليمات لفظية فقط: "تجول حول الكرسي الأحمر، تحت الحبل، ثم اطأ على كل نقطة"',
      'يجب على الطفل تذكر التسلسل الكامل قبل البدء (حمل الذاكرة العاملة)',
      'وقّت كل جولة — اهدف لتقليل الأخطاء قبل تقليل الوقت',
      'نسخة العصابة (الأطفال الأكبر): التنقل بالتوجيه اللفظي فقط من الأستاذ',
    ],
    equipment: ['chairs, cones, cushions, rope', 'tape', 'optional: blindfold'],
    contraindications: ['severe balance issues without support'],
    psychologyObjective: 'Integrates spatial processing, verbal working memory, and motor planning — the combination directly trains the frontal-parietal attention network, which is underactive in both ADHD and ASD',
    psychologyObjectiveAr: 'يدمج المعالجة المكانية والذاكرة العاملة اللفظية والتخطيط الحركي — التركيبة تدرّب مباشرة شبكة الانتباه الجبهية-الجدارية، الأقل نشاطاً في كلٍّ من ADHD وطيف التوحد',
  },

  // ══════════════════════════════════════════════════════════════
  // ㉕ إدارة القلق — التهدئة الحسية السريعة
  // ══════════════════════════════════════════════════════════════
  {
    title: '5-4-3-2-1 Grounding Technique',
    titleAr: 'تقنية التأريض 5-4-3-2-1',
    description: 'Sensory grounding technique for anxiety and overwhelm: anchors the child to the present moment using all 5 senses — immediate intervention for meltdowns and panic',
    descriptionAr: 'تقنية التأريض الحسي للقلق والإرهاق: تُرسّخ الطفل في اللحظة الحاضرة بالحواس الخمس — تدخل فوري للانهيارات والذعر',
    category: 'sensory',
    ageGroups: ['5-11', '12-17', '18-22'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 5,
    points: 20,
    instructions: [
      '5 THINGS YOU CAN SEE — name them aloud: "I see a chair, a window..."',
      '4 THINGS YOU CAN TOUCH — physically touch each one: desk, shirt, floor, chair',
      '3 THINGS YOU CAN HEAR — listen carefully: fan, voices, birds...',
      '2 THINGS YOU CAN SMELL — take deep breaths: paper, grass, food...',
      '1 THING YOU CAN TASTE — notice any taste in your mouth',
      'Take 3 slow breaths after completing. Rate anxiety 1-10 before and after.',
    ],
    instructionsAr: [
      '5 أشياء تراها — سمِّها بصوت عالٍ: "أرى كرسياً، نافذة..."',
      '4 أشياء تلمسها — الملسها فعلياً واحدة تلو الأخرى: طاولة، قميص، أرض، كرسي',
      '3 أشياء تسمعها — استمع جيداً: مروحة، أصوات، طيور...',
      'شيئان تشمهما — خذ أنفاساً عميقة: ورق، عشب، طعام...',
      'شيء واحد تتذوقه — ألاحظ أي طعم في فمك',
      'خذ 3 أنفاس بطيئة بعد الانتهاء. قيّم القلق 1-10 قبل وبعد.',
    ],
    equipment: [],
    contraindications: [],
    psychologyObjective: 'CBT sensory grounding: interrupts the amygdala hijack by forcing prefrontal cortex engagement through deliberate sensory cataloguing; Shapiro (2018) shows 73% reduction in acute anxiety within 2 minutes',
    psychologyObjectiveAr: 'التأريض الحسي CBT: يقاطع اختطاف اللوزة الدماغية بإجبار الفص الجبهي على الانخراط من خلال الجرد الحسي المتعمد؛ شابيرو (2018) يُظهر انخفاضاً بنسبة 73% في القلق الحاد خلال دقيقتين',
  },
]
