// مكتبة التمارين — Adapted Physical Activity (APA) + تمارين التركيز والانتباه
import type { Exercise } from './types'

export const DEFAULT_EXERCISES: Omit<Exercise, 'id' | 'createdAt'>[] = [

  // ══════════════════════════════════════════════════════════════
  // ① تمارين حركية (Motor) — 5-11 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Animal Walk Circuit',
    titleAr: 'دائرة مشية الحيوانات',
    description: 'Children imitate animal movements to develop motor coordination and burn excess energy',
    descriptionAr: 'يقلد الأطفال حركات الحيوانات لتطوير التنسيق الحركي وتفريغ الطاقة الزائدة',
    category: 'motor',
    ageGroups: ['5-11'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 10,
    points: 30,
    instructions: [
      'Start by walking like a bear (hands and feet on floor)',
      'Switch to frog jumps for 30 seconds',
      'Crawl like a snake for 1 minute',
      'Gallop like a horse to finish',
    ],
    instructionsAr: [
      'ابدأ بالمشي مثل الدب (اليدان والقدمان على الأرض)',
      'انتقل إلى القفز مثل الضفدع لمدة 30 ثانية',
      'ازحف مثل الأفعى لمدة دقيقة',
      'اركض مثل الحصان لإنهاء التمرين',
    ],
    equipment: [],
    contraindications: ['joint pain'],
    psychologyObjective: 'Reduce hyperactivity through structured movement with clear rules',
    psychologyObjectiveAr: 'تخفيف فرط الحركة من خلال حركة منظمة بقواعد واضحة',
  },

  // ══════════════════════════════════════════════════════════════
  // ② تمارين التوازن (Balance) — 5-11 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Balance Beam Walk',
    titleAr: 'المشي على خط التوازن',
    description: 'Walking along a taped line on the floor to improve balance and visual focus',
    descriptionAr: 'المشي على خط شريط لتحسين التوازن والتركيز البصري',
    category: 'balance',
    ageGroups: ['5-11'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 8,
    points: 25,
    instructions: [
      'Use tape to make a straight line 3 meters long on the floor',
      'Walk heel-to-toe along the line without stepping off',
      'Arms extended sideways for balance',
      'Repeat 5 times, rest between rounds',
    ],
    instructionsAr: [
      'ضع شريطاً مستقيماً على الأرض بطول 3 أمتار',
      'امشِ بوضع كعب القدم أمام أصابع القدم الأخرى دون الخروج عن الخط',
      'مد ذراعيك للجانبين للتوازن',
      'كرر 5 مرات مع الراحة بين الجولات',
    ],
    equipment: ['masking tape'],
    contraindications: [],
    psychologyObjective: 'Improve vestibular processing and sustained visual attention',
    psychologyObjectiveAr: 'تحسين المعالجة الدهليزية والانتباه البصري المستمر',
  },

  // ══════════════════════════════════════════════════════════════
  // ③ تمارين التركيز والانتباه — 5-11 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Bubble Breathing',
    titleAr: 'تنفس الفقاعات',
    description: 'Slow diaphragmatic breathing to activate the parasympathetic system and sharpen focus',
    descriptionAr: 'تنفس بطني بطيء لتنشيط الجهاز العصبي السمبثاوي وتحسين التركيز',
    category: 'focus',
    ageGroups: ['5-11'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 5,
    points: 20,
    instructions: [
      'Sit comfortably and imagine holding a bubble wand',
      'Breathe in slowly through the nose for 4 counts',
      'Breathe out very slowly through pursed lips to "blow the bubble" for 8 counts',
      'Repeat 8 times — try to make each bubble bigger',
    ],
    instructionsAr: [
      'اجلس بشكل مريح وتخيل أنك تمسك عصا الفقاعات',
      'خذ نفساً ببطء من الأنف لعد 4',
      'أخرج الهواء ببطء شديد من شفتين مضمومتين لعد 8 "لنفخ الفقاعة"',
      'كرر 8 مرات — حاول جعل كل فقاعة أكبر',
    ],
    equipment: ['bubble wand (optional)'],
    contraindications: ['respiratory conditions'],
    psychologyObjective: 'Activate parasympathetic nervous system; the extended exhale reduces cortisol and prepares prefrontal cortex for focused work',
    psychologyObjectiveAr: 'تنشيط الجهاز العصبي السمبثاوي؛ الزفير الممتد يخفض الكورتيزول ويهيئ الفص الجبهي للتركيز',
  },
  {
    title: 'Stop & Listen Game',
    titleAr: 'لعبة قف واسمع',
    description: 'Selective auditory attention game — child must respond only to a target sound and ignore distractors',
    descriptionAr: 'لعبة الانتباه السمعي الانتقائي — يستجيب الطفل للصوت المستهدف ويتجاهل المشتتات',
    category: 'focus',
    ageGroups: ['5-11'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'beginner',
    durationMinutes: 8,
    points: 35,
    instructions: [
      'Agree on one target sound (e.g., clap = freeze, snap = jump)',
      'Move freely around the space',
      'Adult makes random sounds — child must identify and respond to target only',
      'Increase speed and add more distractors as child improves',
    ],
    instructionsAr: [
      'اتفق مع الطفل على صوت مستهدف (مثال: تصفيق = تجمّد، طرق = اقفز)',
      'تحرك بحرية في المساحة',
      'يصدر المشرف أصواتاً عشوائية — يجب على الطفل التعرف على الصوت المستهدف فقط والاستجابة له',
      'زد السرعة وأضف مشتتات أكثر كلما تحسّن الطفل',
    ],
    equipment: [],
    contraindications: ['hearing sensitivity'],
    psychologyObjective: 'Train selective attention and inhibitory control — core deficits in ADHD',
    psychologyObjectiveAr: 'تدريب الانتباه الانتقائي وكبح الاستجابة — الجانبان الأساسيان العجزان في ADHD',
  },
  {
    title: 'Target Toss Focus',
    titleAr: 'قذف الهدف المركّز',
    description: 'Throwing a beanbag at numbered targets on the wall — combines sustained attention with motor control',
    descriptionAr: 'رمي كيس القماش على أهداف مرقمة — يجمع بين الانتباه المستمر والتحكم الحركي',
    category: 'focus',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 10,
    points: 40,
    instructions: [
      'Stick numbered circles (1–5) on a wall at different heights',
      'Adult calls a number — child must hit that target only',
      'Stand 2 meters away; increase distance as accuracy improves',
      'Score 5 hits in a row without error = level up',
    ],
    instructionsAr: [
      'الصق دوائر مرقمة (1–5) على الجدار بارتفاعات مختلفة',
      'يصرخ المشرف برقم — يجب على الطفل ضرب ذلك الهدف فقط',
      'الوقوف على بُعد 2 متر؛ زد المسافة مع تحسن الدقة',
      'تسجيل 5 إصابات متتالية دون خطأ = انتقال للمستوى التالي',
    ],
    equipment: ['beanbags', 'colored paper circles', 'tape'],
    contraindications: [],
    psychologyObjective: 'Build sustained attention span and goal-directed behavior through immediate visual feedback',
    psychologyObjectiveAr: 'بناء مدة الانتباه المستمر والسلوك الهادف من خلال التغذية الراجعة البصرية الفورية',
  },
  {
    title: 'Visual Tracking Trail',
    titleAr: 'تمرين تتبع البصر',
    description: 'Follow a slow-moving object with eyes only (no head movement) — foundational for reading and sustained attention',
    descriptionAr: 'تتبع جسم يتحرك ببطء بالعينين فقط (دون تحريك الرأس) — أساسي للقراءة والانتباه المستمر',
    category: 'focus',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 6,
    points: 25,
    instructions: [
      'Child sits still, head held steady',
      'Adult moves a bright pen or small toy slowly in H, X, and circle patterns',
      'Child follows with eyes only — no head turning',
      '3 rounds of 90 seconds, rest 30 seconds between rounds',
    ],
    instructionsAr: [
      'يجلس الطفل بثبات مع تثبيت الرأس',
      'يحرك المشرف قلماً ملوناً أو لعبة صغيرة ببطء في أنماط H و X ودائرة',
      'يتابع الطفل بعينيه فقط — دون تدوير الرأس',
      '3 جولات لمدة 90 ثانية مع راحة 30 ثانية بين الجولات',
    ],
    equipment: ['bright pen or small toy'],
    contraindications: ['visual impairments'],
    psychologyObjective: 'Strengthen oculomotor control and smooth pursuit — directly linked to reading fluency and sustained attention',
    psychologyObjectiveAr: 'تقوية التحكم الحركي للعين والمتابعة السلسة — مرتبطان مباشرة بطلاقة القراءة والانتباه المستمر',
  },

  // ══════════════════════════════════════════════════════════════
  // ④ تمارين الحسية (Sensory) — 5-11 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Sensory Body Scan',
    titleAr: 'مسح الجسم الحسي',
    description: 'Guided body awareness exercise to develop interoception and calm the sensory system',
    descriptionAr: 'تمرين توعية جسدية موجّهة لتطوير الاستقبال الداخلي وتهدئة الجهاز الحسي',
    category: 'sensory',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 8,
    points: 20,
    instructions: [
      'Lie down or sit comfortably with eyes closed',
      'Notice feet — are they warm or cold? Heavy or light?',
      'Move attention slowly upward: ankles, knees, hips, belly, chest, shoulders, face',
      'Take one slow breath at each body part',
    ],
    instructionsAr: [
      'استلقِ أو اجلس بشكل مريح مع إغماض العينين',
      'انتبه للقدمين — هل هما دافئتان أم باردتان؟ ثقيلتان أم خفيفتان؟',
      'انقل الانتباه ببطء للأعلى: الكاحلان، الركبتان، الوركان، البطن، الصدر، الكتفان، الوجه',
      'خذ نفساً بطيئاً عند كل جزء من الجسم',
    ],
    equipment: ['yoga mat'],
    contraindications: [],
    psychologyObjective: 'Develop interoceptive awareness — critical for emotion regulation and self-monitoring in autism spectrum',
    psychologyObjectiveAr: 'تطوير الوعي الاستقبالي الداخلي — أساسي لتنظيم المشاعر والمراقبة الذاتية في طيف التوحد',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑤ تمارين الإيقاع والتنسيق (Motor) — 12-17 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Rhythm Coordination Drill',
    titleAr: 'تمرين الإيقاع والتنسيق',
    description: 'Clapping and stepping patterns to music — builds bilateral coordination and executive function',
    descriptionAr: 'أنماط التصفيق والخطوات على الموسيقى — يبني التنسيق الثنائي والوظيفة التنفيذية',
    category: 'motor',
    ageGroups: ['12-17'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 15,
    points: 50,
    instructions: [
      'Play steady rhythm music at 120 BPM',
      'Clap on beat 1 and 3 for 30 seconds',
      'Add step left on beat 1, step right on beat 3',
      'Progress to complex patterns as coordination improves',
    ],
    instructionsAr: [
      'شغّل موسيقى إيقاعية ثابتة',
      'صفق عند الإيقاع 1 و3 لمدة 30 ثانية',
      'أضف خطوة يسار عند 1، خطوة يمين عند 3',
      'تقدم إلى أنماط أكثر تعقيداً عند تحسن التنسيق',
    ],
    equipment: ['music player'],
    contraindications: ['hearing sensitivity'],
    psychologyObjective: 'Improve executive function through rhythmic bilateral coordination — activates cerebellum-prefrontal circuits',
    psychologyObjectiveAr: 'تحسين الوظيفة التنفيذية من خلال التنسيق الثنائي الإيقاعي — ينشط دوائر المخيخ الجبهية',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑥ تمارين التركيز المتقدمة — 12-17 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Motor Sequencing Challenge',
    titleAr: 'تحدي التسلسل الحركي',
    description: 'Memorise and reproduce increasingly long movement sequences — trains working memory and sustained attention',
    descriptionAr: 'حفظ وإعادة إنتاج تسلسلات حركية متزايدة الطول — يدرّب الذاكرة العاملة والانتباه المستمر',
    category: 'focus',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'intermediate',
    durationMinutes: 12,
    points: 60,
    instructions: [
      'Start with 3-step sequence: clap–jump–touch knees',
      'Child reproduces the sequence immediately after',
      'Add one new movement every 2 successful rounds',
      'Goal: reach 7-step sequence without error',
    ],
    instructionsAr: [
      'ابدأ بتسلسل من 3 خطوات: تصفيق — قفز — لمس الركبتين',
      'يُعيد الطفل التسلسل فوراً بعد رؤيته',
      'أضف حركة جديدة كل جولتين ناجحتين',
      'الهدف: الوصول إلى تسلسل من 7 خطوات دون خطأ',
    ],
    equipment: [],
    contraindications: [],
    psychologyObjective: 'Directly exercise working memory capacity and inhibitory control — the two core executive functions most impaired in ADHD',
    psychologyObjectiveAr: 'تدريب مباشر لسعة الذاكرة العاملة وكبح الاستجابة — أكثر وظيفتين تنفيذيتين تأثراً في ADHD',
  },
  {
    title: 'Box Breathing 4-4-4-4',
    titleAr: 'التنفس الصندوقي 4-4-4-4',
    description: 'Military-grade breathing protocol used by elite forces to achieve rapid mental calm and sharp focus',
    descriptionAr: 'بروتوكول التنفس العسكري المستخدم في القوات الخاصة لتحقيق هدوء ذهني سريع وتركيز حاد',
    category: 'focus',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 6,
    points: 30,
    instructions: [
      'Sit upright, spine tall, feet flat on floor',
      'Exhale completely to empty lungs',
      'Inhale through nose for 4 counts',
      'Hold breath for 4 counts',
      'Exhale through mouth for 4 counts',
      'Hold empty for 4 counts — that is one cycle',
      'Complete 6 full cycles',
    ],
    instructionsAr: [
      'اجلس منتصباً، العمود الفقري مستقيم، القدمان مسطحتان على الأرض',
      'أخرج الهواء تماماً لإفراغ الرئتين',
      'استنشق من الأنف لعد 4',
      'احبس النفس لعد 4',
      'أخرج الهواء من الفم لعد 4',
      'احتفظ بالرئتين فارغتين لعد 4 — هذه دورة واحدة',
      'أكمل 6 دورات كاملة',
    ],
    equipment: [],
    contraindications: ['asthma', 'respiratory conditions'],
    psychologyObjective: 'Rapidly shift autonomic nervous system from sympathetic (fight/flight) to parasympathetic state; proven to reduce anxiety and restore prefrontal cortex function within 90 seconds',
    psychologyObjectiveAr: 'تحويل سريع للجهاز العصبي اللاإرادي من حالة التعاطف (قتال/هروب) إلى حالة السمبثاوي؛ مثبت علمياً في تخفيض القلق واستعادة وظيفة الفص الجبهي خلال 90 ثانية',
  },
  {
    title: 'Focused Listening Protocol',
    titleAr: 'بروتوكول الاستماع المركّز',
    description: 'Selective auditory attention training — identify target sounds within layered background noise',
    descriptionAr: 'تدريب الانتباه السمعي الانتقائي — تحديد الأصوات المستهدفة ضمن ضجيج خلفي متعدد الطبقات',
    category: 'focus',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 10,
    points: 45,
    instructions: [
      'Play ambient background sounds (market, nature)',
      'Instructor reads a list of words — child must tap when hearing a pre-agreed target word category (e.g., "any fruit name")',
      'Start with 60-second clips, increase to 3-minute clips',
      'Track accuracy: hits / total target words × 100%',
    ],
    instructionsAr: [
      'شغّل أصوات خلفية (سوق، طبيعة)',
      'يقرأ المشرف قائمة كلمات — يجب على الطفل النقر عند سماع فئة الكلمة المستهدفة المتفق عليها (مثال: "أي اسم فاكهة")',
      'ابدأ بمقاطع 60 ثانية، زد إلى مقاطع 3 دقائق',
      'تتبع الدقة: الإصابات ÷ إجمالي الكلمات المستهدفة × 100%',
    ],
    equipment: ['audio player'],
    contraindications: ['hearing sensitivity'],
    psychologyObjective: 'Train selective and sustained auditory attention — directly mirrors classroom demands; builds resistance to distraction',
    psychologyObjectiveAr: 'تدريب الانتباه السمعي الانتقائي والمستمر — يحاكي مباشرة متطلبات الفصل الدراسي؛ يبني المقاومة للمشتتات',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑦ الاسترخاء العضلي (Sensory/Regulation) — 12-17, 18-22
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Progressive Muscle Relaxation',
    titleAr: 'الاسترخاء العضلي التدريجي',
    description: 'Systematic tension-and-release of muscle groups — reduces cortisol and prepares the nervous system for focus',
    descriptionAr: 'توتير وإرخاء منهجي لمجموعات العضلات — يخفض الكورتيزول ويهيئ الجهاز العصبي للتركيز',
    category: 'sensory',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 12,
    points: 40,
    instructions: [
      'Lie down comfortably on a mat',
      'Tense your feet muscles tightly for 5 seconds',
      'Release completely and notice the contrast',
      'Move progressively upward: calves → thighs → abdomen → chest → arms → face',
      'Breathe slowly throughout; never hold breath while tensing',
    ],
    instructionsAr: [
      'استلقِ بشكل مريح على حصيرة',
      'شدّ عضلات قدميك بقوة لمدة 5 ثوانٍ',
      'أرخِ تماماً ولاحظ الفرق',
      'تقدم تدريجياً للأعلى: الساق → الفخذ → البطن → الصدر → الذراعان → الوجه',
      'تنفس ببطء طوال التمرين؛ لا تحبس النفس أثناء الشد',
    ],
    equipment: ['yoga mat'],
    contraindications: ['muscle injuries'],
    psychologyObjective: 'Develop somatic self-regulation; body awareness is foundational for recognising and managing emotional dysregulation',
    psychologyObjectiveAr: 'تطوير التنظيم الجسدي الذاتي؛ الوعي بالجسم أساسي للتعرف على ضعف التنظيم العاطفي وإدارته',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑧ تمارين التركيز والانتباه المتقدمة — 18-22 سنة
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Mindful Strength Circuit',
    titleAr: 'دائرة القوة اليقظة',
    description: 'Bodyweight exercises fused with mindfulness cues — builds physical strength and mental attention simultaneously',
    descriptionAr: 'تمارين وزن الجسم مع توجيهات اليقظة الذهنية — يبني القوة الجسدية والانتباه الذهني في آنٍ واحد',
    category: 'energy',
    ageGroups: ['18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 20,
    points: 75,
    instructions: [
      'Start with 60 seconds mindful breathing',
      'Perform 10 slow push-ups focusing on every muscle contraction',
      '20 squats with deep breathing rhythm: inhale down, exhale up',
      '30-second plank with full attention on core engagement',
      'End with 2 minutes of body scan meditation',
    ],
    instructionsAr: [
      'ابدأ بـ 60 ثانية من التنفس اليقظ',
      'اعمل 10 تمارين ضغط ببطء مع التركيز على كل تقلص عضلي',
      '20 قرفصاء مع إيقاع تنفس عميق: استنشق عند النزول، أخرج الهواء عند الصعود',
      'تمرين الألواح 30 ثانية مع التركيز الكامل على انقباض العضلة المركزية',
      'اختم بـ 2 دقيقة من مسح الجسم التأملي',
    ],
    equipment: ['yoga mat'],
    contraindications: ['upper body injuries', 'cardiac conditions'],
    psychologyObjective: 'Channel excess energy into structured strength; mindfulness cues force sustained attention during physical effort — a dual-task that significantly improves attentional capacity',
    psychologyObjectiveAr: 'توجيه الطاقة الزائدة لعمل القوة؛ توجيهات اليقظة تُجبر على الانتباه المستمر أثناء المجهود الجسدي — مهمة مزدوجة تحسّن بشكل ملحوظ القدرة الانتباهية',
  },
  {
    title: 'Attention Rebuild Protocol',
    titleAr: 'بروتوكول إعادة بناء الانتباه',
    description: 'Scientifically-structured 20-min session combining breathing, movement bursts, and single-focus tasks to systematically rebuild the attention span',
    descriptionAr: 'جلسة 20 دقيقة مبنية علمياً تجمع التنفس وانفجارات الحركة ومهام التركيز الواحد لإعادة بناء الانتباه بشكل منهجي',
    category: 'focus',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'advanced',
    durationMinutes: 20,
    points: 90,
    instructions: [
      'Phase 1 — Reset (4 min): Box breathing 4-4-4-4 × 4 cycles',
      'Phase 2 — Activate (3 min): 30 jumping jacks at full speed to raise dopamine',
      'Phase 3 — Focus task (8 min): Read a paragraph aloud slowly, one sentence at a time; stop and summarise after each sentence',
      'Phase 4 — Cool down (5 min): Progressive muscle relaxation, starting from feet',
      'Track: how many sentences could you summarise correctly?',
    ],
    instructionsAr: [
      'المرحلة 1 — إعادة الضبط (4 دقائق): التنفس الصندوقي 4-4-4-4 × 4 دورات',
      'المرحلة 2 — التنشيط (3 دقائق): 30 قفزة نجمة بكامل السرعة لرفع الدوبامين',
      'المرحلة 3 — مهمة التركيز (8 دقائق): اقرأ فقرة بصوت عالٍ ببطء، جملة في كل مرة؛ توقف وسرّد ما فهمته بعد كل جملة',
      'المرحلة 4 — التهدئة (5 دقائق): الاسترخاء العضلي التدريجي، ابدأ من القدمين',
      'تتبع: كم جملة تمكنت من تلخيصها بشكل صحيح؟',
    ],
    equipment: ['yoga mat', 'text passage'],
    contraindications: ['cardiac conditions'],
    psychologyObjective: 'Integrates the full neurological reset cycle: parasympathetic activation → dopamine boost → prefrontal engagement → somatic consolidation; evidence base: Ratey J., "Spark" (2008)',
    psychologyObjectiveAr: 'يدمج دورة إعادة الضبط العصبي الكاملة: تنشيط سمبثاوي → رفع دوبامين → إشراك الفص الجبهي → توطيد جسدي؛ المرجع العلمي: Ratey J.، "Spark" (2008)',
  },
  {
    title: 'Distraction Inoculation Training',
    titleAr: 'تدريب التحصين من التشتت',
    description: 'Deliberately practice focusing under increasing distraction conditions — builds distraction immunity for real-world demands',
    descriptionAr: 'ممارسة التركيز عمداً في ظروف مشتتة متزايدة — يبني مناعة التشتت لمتطلبات العالم الحقيقي',
    category: 'focus',
    ageGroups: ['12-17', '18-22'],
    diagnoses: ['ADHD', 'ADHD+AUTISM'],
    difficulty: 'advanced',
    durationMinutes: 15,
    points: 80,
    instructions: [
      'Choose a 5-minute task requiring sustained attention (drawing, reading, puzzle)',
      'Round 1 — Silent: complete the task in a quiet room, note any mind-wandering',
      'Round 2 — Background: same task with low-level music or noise',
      'Round 3 — Social: same task with someone walking around or talking nearby',
      'After each round: rate focus 1–10 and note what pulled attention away',
    ],
    instructionsAr: [
      'اختر مهمة من 5 دقائق تتطلب انتباهاً مستمراً (رسم، قراءة، لغز)',
      'الجولة 1 — صامت: أكمل المهمة في غرفة هادئة، لاحظ أي تشتت ذهني',
      'الجولة 2 — خلفية: نفس المهمة مع موسيقى أو ضوضاء خفيفة',
      'الجولة 3 — اجتماعي: نفس المهمة مع شخص يتحرك أو يتحدث بالقرب',
      'بعد كل جولة: قيّم التركيز من 1–10 ولاحظ ما سحب انتباهك',
    ],
    equipment: ['age-appropriate focus task materials'],
    contraindications: [],
    psychologyObjective: 'Graduated exposure to distracting stimuli progressively raises the threshold for attentional disruption — same principle as systematic desensitisation applied to the attentional system',
    psychologyObjectiveAr: 'التعرض التدريجي للمثيرات المشتتة يرفع تدريجياً عتبة الاضطراب الانتباهي — نفس مبدأ التحسيس التدريجي المطبق على النظام الانتباهي',
  },

  // ══════════════════════════════════════════════════════════════
  // ⑨ التفاعل الاجتماعي (Social) — جميع الفئات
  // ══════════════════════════════════════════════════════════════
  {
    title: 'Mirror Movement Game',
    titleAr: 'لعبة الحركة المرايا',
    description: 'Partner mirroring exercise — develops joint attention, turn-taking, and nonverbal communication',
    descriptionAr: 'تمرين ثنائي للمرايا — يطور الانتباه المشترك والتناوب والتواصل غير اللفظي',
    category: 'social',
    ageGroups: ['5-11', '12-17', '18-22'],
    diagnoses: ['AUTISM', 'ADHD+AUTISM'],
    difficulty: 'intermediate',
    durationMinutes: 15,
    points: 60,
    instructions: [
      'Partner A leads slow deliberate movements for 60 seconds; Partner B mirrors exactly',
      'Switch roles — B leads, A mirrors',
      'Progress to moving around the room while maintaining mirroring',
      'Final round: both move with no designated leader — find shared rhythm',
    ],
    instructionsAr: [
      'الشريك أ يقود حركات بطيئة ومتعمدة لمدة 60 ثانية؛ الشريك ب يعكسها بدقة',
      'بدّل الدور — ب يقود، أ يعكس',
      'تقدم للتنقل في الغرفة مع الحفاظ على المرايا',
      'الجولة الأخيرة: كلاهما يتحرك بدون قائد محدد — ابحثا معاً عن الإيقاع المشترك',
    ],
    equipment: [],
    contraindications: [],
    psychologyObjective: 'Activate mirror neuron system; sustained joint attention during mirroring directly exercises the attentional systems most challenged in autism spectrum',
    psychologyObjectiveAr: 'تنشيط نظام الخلايا العصبية المرآتية؛ الانتباه المشترك المستمر أثناء التمثيل الحركي يدرّب مباشرة الأنظمة الانتباهية الأكثر تحدياً في طيف التوحد',
  },
  {
    title: 'Cooperative Ball Pass',
    titleAr: 'تمرير الكرة التعاوني',
    description: 'Group exercise using eye contact and timing to pass a ball — builds social attention and impulse control',
    descriptionAr: 'تمرين جماعي باستخدام التواصل البصري والتوقيت لتمرير الكرة — يبني الانتباه الاجتماعي والتحكم في الاندفاع',
    category: 'social',
    ageGroups: ['5-11', '12-17'],
    diagnoses: ['AUTISM', 'ADHD+AUTISM', 'OTHER'],
    difficulty: 'beginner',
    durationMinutes: 12,
    points: 45,
    instructions: [
      'Form a circle of 3–6 participants',
      'Rule: must make eye contact with the receiver BEFORE passing',
      'Start slow with a soft ball; increase pace gradually',
      'Add challenge: two balls simultaneously after mastery',
    ],
    instructionsAr: [
      'اكوّن دائرة من 3–6 مشاركين',
      'القاعدة: يجب التواصل البصري مع المستلم قبل التمرير',
      'ابدأ ببطء مع كرة ناعمة؛ زد السرعة تدريجياً',
      'أضف تحدياً: كرتان في نفس الوقت بعد إتقان المهارة',
    ],
    equipment: ['soft ball(s)'],
    contraindications: [],
    psychologyObjective: 'Eye contact before action forces inhibitory control; cooperative format builds joint attention and social motivation simultaneously',
    psychologyObjectiveAr: 'التواصل البصري قبل الفعل يُجبر على كبح الاستجابة؛ الصيغة التعاونية تبني الانتباه المشترك والدافعية الاجتماعية في آنٍ واحد',
  },
]
